Alchemy = {
buttonText = "Alchemy",
headerText = "THE ALCHEMIST",
content = {
"------------------------------------------------------------------------------------------------",
"MATERIAL LIST",
"------------------------------------------------------------------------------------------------",
"91 |cFFFFFFFF[Peacebloom]|r",
"45 |cFFFFFFFF[Silverleaf]|r",
"151 |cFF9D9D9D[Empty Vial]|r",
"50 |cFFFFFFFF[Mageroyal]|r",
"54 |cFFFFFFFF[Earthroot]|r",
"60 |cFFFFFFFF[Briarthorn]|r",
"94 |cFFFFFFFF[Stranglekelp]|r",
"40 |cFFFFFFFF[Firefin Snapper]|r",
"51 |cFFFFFFFF[Kingsblood]|r",
"99 |cFF9D9D9D[Leaded Vial]|r",
"48 |cFFFFFFFF[Liferoot]|r",
"45 |cFFFFFFFF[Arthas Tears]|r",
"75 |cFF9D9D9D[Crystal Vial]|r",
"60 |cFFFFFFFF[Sungrass]|r",
"94 |cFFFFFFFF[Blindweed]|r",
"51 |cFFFFFFFF[Plaguebloom]|r",
"17 |cFF9D9D9D[Imbued Vial]|r",
"",
"Main route only. Alternative recipes use different materials.",
"",
"------------------------------------------------------------------------------------------------",
"PREFACE",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"Some |cFF1EFF00Recipes|r may require completing |cFFFFD700[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the |cFFFFFF00[Auction House]|r",
"",
"NOTE: |cFF1EFF00Healing Potions|r are crafted with |cFF1EFF00First Aid|r in Forever, not Alchemy.",
"NOTE: This route is based on Forever beta data.",
"Everything above skill 225 is untested.",
"",
"------------------------------------------------------------------------------------------------",
"LEVELING ALCHEMY",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF1 - 55|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF1-10|r]",
"Craft: 9x |cFFFFFFFF[Minor Arcane Elixir]|r",
"Requires: 9 |cFFFFFFFF[Peacebloom]|r, 9 |cFF9D9D9D[Empty Vial]|r",
"",
"|cFFB2FF66Alternative Recipes|r:",
"      |cFFFFFFFF[Elixir of Minor Force]|r",
"      Requires: 9 |cFFFFFFFF[Silverleaf]|r, 9 |cFF9D9D9D[Empty Vial]|r",
"",
"[|cFF33FFFF10-55|r]",
"Craft: 45x |cFFFFFFFF[Elixir of Minor Defense]|r",
"Requires: 45 |cFFFFFFFF[Silverleaf]|r, 45 |cFFFFFFFF[Peacebloom]|r, 45 |cFF9D9D9D[Empty Vial]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Journeyman Alchemist]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"      Also requires: Alchemy 50",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Yelmak]|r / |cFF33FF99[Orgrimmar, Durotar]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Doctor Marsh]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Bena Winterhoof]|r / |cFF33FF99[Thunder Bluff, Mulgore]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Lilyssia Nightbreeze]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Sylvanna Forestmoon]|r / |cFF33FF99[Darnassus, Teldrassil]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Tally Berryfizz]|r / |cFF33FF99[Ironforge, Dun Morogh]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF55 - 150|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF55-65|r]",
"Craft: 10x |cFFFFFFFF[Minor Mana Potion]|r",
"Requires: 10 |cFFFFFFFF[Mageroyal]|r, 10 |cFFFFFFFF[Peacebloom]|r, 10 |cFF9D9D9D[Empty Vial]|r",
"",
"[|cFF33FFFF65-90|r]",
"Craft: 27x |cFFFFFFFF[Elixir of Minor Fortitude]|r",
"Requires: 54 |cFFFFFFFF[Earthroot]|r, 27 |cFFFFFFFF[Peacebloom]|r, 27 |cFF9D9D9D[Empty Vial]|r",
"",
"NOTE: Turns yellow at 80.",
"",
"[|cFF33FFFF90-120|r]",
"Craft: 30x |cFFFFFFFF[Elixir of Wisdom]|r",
"Requires: 30 |cFFFFFFFF[Mageroyal]|r, 60 |cFFFFFFFF[Briarthorn]|r, 30 |cFF9D9D9D[Empty Vial]|r",
"",
"NOTE: Keep these if you are also leveling Tailoring.",
"",
"[|cFF33FFFF120-130|r]",
"Craft: 10x |cFFFFFFFF[Lesser Mana Potion]|r",
"Requires: 10 |cFFFFFFFF[Mageroyal]|r, 10 |cFFFFFFFF[Stranglekelp]|r, 10 |cFF9D9D9D[Empty Vial]|r",
"",
"[|cFF33FFFF130-150|r]",
"Craft: 20x |cFFFFFFFF[Fire Oil]|r",
"Requires: 40 |cFFFFFFFF[Firefin Snapper]|r, 20 |cFF9D9D9D[Empty Vial]|r",
"",
"NOTE: Each craft makes 2 oils. Keep 30 for Elixir of Fire Power.",
"",
"|cFFB2FF66Alternative Recipes|r:",
"      |cFFFFFFFF[Lesser Mana Potion]|r",
"      Requires: 20 |cFFFFFFFF[Mageroyal]|r, 20 |cFFFFFFFF[Stranglekelp]|r, 20 |cFF9D9D9D[Empty Vial]|r",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Expert Alchemist]|r (Requires Character Level 20; Raises Cap [150] > [225])",
"      Also requires: Alchemy 125, 50 Silver",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Doctor Herbert Halsey]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Ainethil]|r / |cFF33FF99[Darnassus, Teldrassil]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF150 - 225|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF150-165|r]",
"Craft: 15x |cFFFFFFFF[Elixir of Fire Power]|r",
"Requires: 30 |cFFFFFFFF[Fire Oil]|r, 15 |cFFFFFFFF[Kingsblood]|r, 15 |cFF9D9D9D[Leaded Vial]|r",
"",
"|cFFB2FF66Alternative Recipes|r:",
"      |cFFFFFFFF[Lesser Mana Potion]|r",
"      Requires: 22 |cFFFFFFFF[Mageroyal]|r, 22 |cFFFFFFFF[Stranglekelp]|r, 22 |cFF9D9D9D[Empty Vial]|r",
"NOTE: Only if you made Lesser Mana Potions at 130-150.",
"",
"[|cFF33FFFF165-195|r]",
"Craft: 36x |cFFFFFFFF[Mana Potion]|r",
"Requires: 36 |cFFFFFFFF[Stranglekelp]|r, 36 |cFFFFFFFF[Kingsblood]|r, 36 |cFF9D9D9D[Leaded Vial]|r",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Recipe: Nature Protection Potion]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Alchemist Pestlezugg]|r / |cFF33FF99[Gadgetzan, Tanaris]|r",
"      |cFFFFD700[N]|r |cFF33FF99[Glyx Brewright]|r / |cFF33FF99[Booty Bay, Stranglethorn Vale]|r",
"",
"      |cFFFF0000[H]|r |cFF33FF99[Bronk]|r / |cFF33FF99[Camp Mojache, Feralas]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Logannas]|r / |cFF33FF99[Feathermoon Stronghold, Feralas]|r",
"NOTE: Recipe binds when picked up!",
"------------------------------------------------------------------------------------------------",
"",
"[|cFF33FFFF195-225|r]",
"Craft: 36x |cFFFFFFFF[Nature Protection Potion]|r",
"Requires: 36 |cFFFFFFFF[Liferoot]|r, 36 |cFFFFFFFF[Stranglekelp]|r, 36 |cFF9D9D9D[Leaded Vial]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Artisan Alchemist]|r (Requires Character Level 35; Raises Cap [225] > [300])",
"      Also requires: Alchemy 200",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Rogvar]|r / |cFF33FF99[Stonard, Swamp of Sorrows]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Kylanna Windwhisper]|r / |cFF33FF99[Feathermoon Stronghold, Feralas]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF225 - 300|r]",
"------------------------------------------------------------------------------------------------",
"NOTE: Untested in the Forever beta. Verify these steps in game.",
"",
"[|cFF33FFFF225-230|r]",
"Craft: 12x |cFFFFFFFF[Nature Protection Potion]|r",
"Requires: 12 |cFFFFFFFF[Liferoot]|r, 12 |cFFFFFFFF[Stranglekelp]|r, 12 |cFF9D9D9D[Leaded Vial]|r",
"",
"[|cFF33FFFF230-265|r]",
"Craft: 45x |cFFFFFFFF[Draught of Detect Undead]|r",
"Requires: 45 |cFFFFFFFF[Arthas Tears]|r, 45 |cFF9D9D9D[Crystal Vial]|r",
"",
"NOTE: Turns yellow at 245. Buy extra.",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Recipe: Superior Mana Potion]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Algernon]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Ulthir]|r / |cFF33FF99[Darnassus, Teldrassil]|r",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF265-275|r]",
"Craft: 10x |cFFFFFFFF[Superior Mana Potion]|r",
"Requires: 20 |cFFFFFFFF[Sungrass]|r, 20 |cFFFFFFFF[Blindweed]|r, 10 |cFF9D9D9D[Crystal Vial]|r",
"",
"[|cFF33FFFF275-290|r]",
"Craft: 20x |cFFFFFFFF[Superior Mana Potion]|r",
"Requires: 40 |cFFFFFFFF[Sungrass]|r, 40 |cFFFFFFFF[Blindweed]|r, 20 |cFF9D9D9D[Crystal Vial]|r",
"",
"|cFFB2FF66Alternative Recipes|r:",
"      |cFFFFFFFF[Elixir of Greater Defense]|r",
"      Requires: 34 |cFFFFFFFF[Stonescale Oil]|r, 17 |cFFFFFFFF[Sungrass]|r, 17 |cFF9D9D9D[Crystal Vial]|r",
"      |cFFFFFFFF[Elixir of Shadow Power]|r",
"      Requires: 81 |cFFFFFFFF[Ghost Mushroom]|r, 27 |cFF9D9D9D[Crystal Vial]|r",
"NOTE: Make whichever is cheapest on the Auction House.",
"NOTE: Greater Defense is 17 crafts, yellow at 280.",
"Shadow Power is 27 crafts.",
"",
"[|cFF33FFFF290-300|r]",
"Craft: 17x |cFFFFFFFF[Major Frenzy Potion]|r",
"Requires: 51 |cFFFFFFFF[Plaguebloom]|r, 34 |cFFFFFFFF[Blindweed]|r, 17 |cFF9D9D9D[Imbued Vial]|r",
"",
"NOTE: NOT FINALIZED. Turns yellow at 295.",
"Other options grey out at 295.",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Recipe: Major Frenzy Potion]|r (Merchant's Favor vendors)",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Apothecary Durelle]|r / |cFF33FF99[Durotar]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Nina Surefire]|r / |cFF33FF99[Redridge Mountains]|r",
"------------------------------------------------------------------------------------------------"
}
}
