Alchemy = {
buttonText = "Alchemy",
headerText = "THE ALCHEMIST",
content = {
"------------------------------------------------------------------------------------------------",
"MATERIAL LIST",
"------------------------------------------------------------------------------------------------",
"65 |cFFFFFFFF[Peacebloom]|r",
"65 |cFFFFFFFF[Silverleaf]|r",
"85 |cFF9D9D9D[Empty Vial]|r",
"100 |cFFFFFFFF[Briarthorn]|r",
"35 |cFFFFFFFF[Bruiseweed]|r",
"105 |cFF9D9D9D[Leaded Vial]|r",
"20 |cFFFFFFFF[Mageroyal]|r",
"50 |cFFFFFFFF[Stranglekelp]|r",
"35 |cFFFFFFFF[Liferoot]|r",
"35 |cFFFFFFFF[Kingsblood]|r",
"35 |cFFFFFFFF[Goldthorn]|r",
"5 |cFFFFFFFF[Wild Steelbloom]|r",
"75 |cFFFFFFFF[Sungrass]|r",
"15 |cFFFFFFFF[Khadgars Whisker]|r",
"120 |cFF9D9D9D[Crystal Vial]|r",
"45 |cFFFFFFFF[Arthas Tears]|r",
"60 |cFFFFFFFF[Blindweed]|r",
"75 |cFFFFFFFF[Golden Sansam]|r",
"20 |cFFFFFFFF[Mountain Silversage]|r",
"",
"------------------------------------------------------------------------------------------------",
"PREFACE",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"Some |cFF1EFF00Recipes|r may require completing |cFFFFD700[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the |cFFFFFF00[Auction House]|r",
"",
"------------------------------------------------------------------------------------------------",
"LEVELING ALCHEMY",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF1 - 60|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF1-60|r]",
"Craft: 65x |cFFFFFFFF[Minor Healing Potion]|r",
"Requires: 65 |cFFFFFFFF[Peacebloom]|r, 65 |cFFFFFFFF[Silverleaf]|r, 65 |cFF9D9D9D[Empty Vial]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Journeyman Alchemist]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Yelmak]|r / |cFF33FF99[Orgrimmar, Durator]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Doctor Marsh]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Bena Winterhoof]|r / |cFF33FF99[Thunder Bluff, Mulgore]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Lilyssia Nightbreeze]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Sylvanna Forestmoon]|r / |cFF33FF99[Darnassus, Teldrassil]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Tally Berryfizz]|r / |cFF33FF99[Ironforge, Dun Morogh]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF60 - 140|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF60-110|r]",
"Craft: 65x |cFFFFFFFF[Lesser Healing Potion]|r",
"Requires: 65 |cFFFFFFFF[Minor Healing Potion]|r, 65 |cFFFFFFFF[Briarthorn]|r",
"",
"[|cFF33FFFF110-140|r]",
"Craft: 35x |cFFFFFFFF[Healing Potion]|r",
"Requires: 35 |cFFFFFFFF[Bruiseweed]|r, 35 |cFFFFFFFF[Briarthorn]|r, 35 |cFF9D9D9D[Leaded Vial]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Expert Alchemist]|r (Requires Character Level 20; Raises Cap [150] > [225])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Doctor Herbert Halsey]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Ainethil]|r / |cFF33FF99[Darnassus, Teldrassil]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF[|cFF33FFFFLevels:|r]|r] [|cFF33FFFF140 - 155|r]",
"------------------------------------------------------------------------------------------------",
"Craft: 20x |cFFFFFFFF[Lesser Mana Potion]|r",
"Requires: 20 |cFFFFFFFF[Mageroyal]|r, 20 |cFFFFFFFF[Stranglekelp]|r, 20 |cFF9D9D9D[Empty Vial]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF155 - 185|r]",
"------------------------------------------------------------------------------------------------",
"Craft: 35x |cFFFFFFFF[Greater Healing Potion]|r",
"Requires: 35 |cFFFFFFFF[Liferoot]|r, 35 |cFFFFFFFF[Kingsblood]|r, 35 |cFF9D9D9D[Leaded Vial]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF185 - 210|r]",
"------------------------------------------------------------------------------------------------",
"Craft: 30x |cFFFFFFFF[Elixir of Agility]|r",
"Requires: 30 |cFFFFFFFF[Stranglekelp]|r, 30 |cFFFFFFFF[Goldthorn]|r, 30 |cFF9D9D9D[Leaded Vial]|r",
"",
"|cFFB2FF66Alternative Recipes|r:",
"      |cFFFFFFFF[Mana Potion]|r",
"      Requires: |cFFFFFFFF[Stranglekelp]|r, |cFFFFFFFF[Kingsblood]|r, |cFF9D9D9D[Leaded Vial]|r", 
"      |cFFFFFFFF[Lesser Invisibility Potion]|r",
"      Requires: |cFFFFFFFF[Stranglekelp]|r, |cFFFFFFFF[Goldthorn]|r, |cFF9D9D9D[Leaded Vial]|r",
"      |cFFFFFFFF[Nature Protection Potion]|r",
"      Requires: |cFFFFFFFF[Stranglekelp]|r, |cFFFFFFFF[Liferoot]|r, |cFF9D9D9D[Leaded Vial]|r",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Recipe: Nature Protection Potion]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Alchemist Pestlezugg]|r / |cFF33FF99[Gadgetzan, Tanaris]|r",
"      |cFFFFD700[N]|r |cFF33FF99[Glyx Brewright]|r / |cFF33FF99[Booty Bay, Stranglethorn Vale]|r|r",
"",
"      |cFFFF0000[H]|r |cFF33FF99[Bronk]|r / |cFF33FF99[Camp Mojache, Feralas]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Logannas]|r / |cFF33FF99[Feathermoon Stronghold, Feralas]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:", 
"      |cFF1EFF00[Artisan Alchemist]|r (Requires Character Level 35; Raises Cap [225] > [300])",
"WHERE:", 
"      |cFFFF0000[H]|r |cFF33FF99[Rogvar]|r / |cFF33FF99[Stonard, Swamp of Sorrows]|r", 
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Kylanna Windwhisper]|r / |cFF33FF99[Feathermoon Stronghold, Feralas]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF210 - 265|r]",
"------------------------------------------------------------------------------------------------",
"|cFFFFFFFF[|cFF33FFFF210-215|r]|r",
"Craft: 5x |cFFFFFFFF[Elixir of Greater Defense]|r",
"Requires: 5 |cFFFFFFFF[Wild Steelbloom]|r, 5 |cFFFFFFFF[Goldthorn]|r, 5 |cFF9D9D9D[Leaded Vial]|r",
"",
"|cFFFFFFFF[|cFF33FFFF215-230|r]|r",
"Craft: 15x |cFFFFFFFF[Superior Healing Potion]|r",
"Requires: 15 |cFFFFFFFF[Sungrass]|r, 15 |cFFFFFFFF[Khadgars Whisker]|r, 15 |cFF9D9D9D[Crystal Vial]|r",
"",
"|cFFFFFFFF[|cFF33FFFF230-265|r]|r",
"Craft: 45x |cFFFFFFFF[Elixir of Detect Undead]|r",
"Requires: 45 |cFFFFFFFF[Arthas Tears]|r, 45 |cFF9D9D9D[Crystal Vial]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF265 - 285|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Recipe: Superior Mana Potion]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Algernon]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Ulthir]|r / |cFF33FF99[Darnassus, Teldrassil]|r",
"------------------------------------------------------------------------------------------------",
"Craft: 30x |cFFFFFFFF[Superior Mana Potion]|r",
"Requires: 60 |cFFFFFFFF[Sungrass]|r, 60 |cFFFFFFFF[Blindweed]|r, 30 |cFF9D9D9D[Crystal Vial]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF285 - 300|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Recipe: Major Healing Potion]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Evie Whirlbrew]|r / |cFF33FF99[Everlook, Winterspring]|r",
"------------------------------------------------------------------------------------------------",
"Craft: 20x |cFFFFFFFF[Major Healing Potion]|r",
"Requires: 40 |cFFFFFFFF[Golden Sansam]|r, 20 |cFFFFFFFF[Mountain Silversage]|r, 20 |cFF9D9D9D[Crystal Vial]|r"
}
}