Blacksmithing = {
buttonText = "Blacksmithing",
headerText = "THE BLACKSMITH",
content = {
"------------------------------------------------------------------------------------------------",
"MATERIAL LIST",
"------------------------------------------------------------------------------------------------",
"150 |cFFFFFFFF[Rough Stone]|r",
"150 |cFFFFFFFF[Copper Bar]|r",
"95 |cFFFFFFFF[Coarse Stone]|r",
"5 |cFF00FF00[Silver Bar]|r",
"140 |cFFFFFFFF[Bronze Bar]|r",
"105 |cFFFFFFFF[Heavy Stone]|r",
"5 |cFF00FF00[Gold Bar]|r",
"230 |cFFFFFFFF[Iron Bar]|r",
"35 |cFFFFFFFF[Green Dye]|r",
"190 |cFFFFFFFF[Steel Bar]|r",
"520 |cFFFFFFFF[Solid Stone]|r",
"60 |cFFFFFFFF[Mageweave Cloth]|r",
"250 |cFFFFFFFF[Mithril Bar]|r",
"20 |cFFFFFFFF[Dense Stone]|r",
"730 |cFFFFFFFF[Thorium Bar]|r",
"30 |cFF00FF00[Star Ruby]|r",
"5 |cFF00FF00[Aquamarine]|r",
"",
"------------------------------------------------------------------------------------------------",
"PREFACE",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"Some |cFF1EFF00Plans|r may require completing |cFFFFD700[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the |cFFFFFF00[Auction House]|r",
"",
"------------------------------------------------------------------------------------------------",
"LEVELING BLACKSMITHING",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF1 - 75|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF1-30|r]",
"Craft: 40x |cFFFFFFFF[Rough Sharpening Stone]|r",
"Requires: 40 |cFFFFFFFF[Rough Stone]|r",
"",
"[|cFF33FFFF30-65|r]",
"Craft: 55x |cFFFFFFFF[Rough Grinding Stone]|r",
"Requires: 110 |cFFFFFFFF[Rough Stone]|r",
"NOTE: Save 10 |cFFFFFFFF[Rough Grinding Stone]|r for later use",
"",
"[|cFF33FFFF65-75|r]",
"Craft: 25x |cFFFFFFFF[Coarse Sharpening Stone]|r",
"Requires: 25 |cFFFFFFFF[Coarse Stone]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Journeyman Blacksmith]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Snarl]|r / |cFF33FF99[Orgrimmar, Durotar]|r",
"      |cFFFF0000[H]|r |cFF33FF99[James Van Brunt]|r / |cFF33FF99[Undercity]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Karn Stonehoof]|r / |cFF33FF99[Thunder Bluff, Mulgore]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Rotgath Stonebeard]|r / |cFF33FF99[Ironforge, Dun Morogh]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Therum Deepforge]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF75 - 125|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF75-90|r]",
"Craft: 35x |cFFFFFFFF[Coarse Grinding Stone]|r",
"Requires: 70 |cFFFFFFFF[Coarse Stone]|r",
"NOTE: Save the |cFFFFFFFF[Coarse Grinding Stone]|r for later",
"",
"[|cFF33FFFF90-100|r]",
"Craft: 10x |cFFFFFFFF[Runed Copper Belt]|r",
"Requires: 100 |cFFFFFFFF[Copper Bar]|r",
"",
"[|cFF33FFFF100-105|r]",
"Craft: 5x |cFFFFFFFF[Silver Rod]|r",
"Requires: 5 |cFF00FF00[Silver Bar]|r, 10 |cFFFFFFFF[Rough Grinding Stone]|r",
"NOTE: If you don't have the |cFF00FF00[Silver Bar]|r, make more |cFFFFFFFF[Runed Copper Belt]|r",
"",
"[|cFF33FFFF105-110|r]",
"Craft: 5x |cFFFFFFFF[Runed Copper Belt]|r",
"Requires: 50 |cFFFFFFFF[Copper Bar]|r",
"",
"[|cFF33FFFF110-125|r]",
"Craft: 15x |cFFFFFFFF[Rough Bronze Leggings]|r",
"Requires: 90 |cFFFFFFFF[Bronze Bar]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Expert Blacksmith]|r (Requires Character Level 20; Raises Cap [150] > [225])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Saru Steelfury]|r / |cFF33FF99[Orgrimmar, Durotar]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Bengus Deepforge]|r / |cFF33FF99[Ironforge, Dun Morogh]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF125 - 225|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF125-140|r]",
"Craft: 35x |cFFFFFFFF[Heavy Grinding Stone]|r",
"Requires: 105 |cFFFFFFFF[Heavy Stone]|r",
"NOTE: Save |cFFFFFFFF[Heavy Grinding Stone]|r for later",
"",
"[|cFF33FFFF140-150|r]",
"Craft: 10x |cFFFFFFFF[Patterned Bronze Bracers]|r",
"Requires: 50 |cFFFFFFFF[Bronze Bar]|r, 20 |cFFFFFFFF[Coarse Grinding Stone]|r",
"",
"[|cFF33FFFF150-155|r]",
"Craft: 5x |cFFFFFFFF[Golden Rod]|r",
"Requires: 5 |cFF00FF00[Gold Bar]|r, 10 |cFFFFFFFF[Coarse Grinding Stone]|r",
"",
"[|cFF33FFFF155-165|r]",
"Craft: 10x |cFFFFFFFF[Green Iron Leggings]|r",
"Requires: 80 |cFFFFFFFF[Iron Bar]|r, 10 |cFFFFFFFF[Heavy Grinding Stone]|r, 10 |cFFFFFFFF[Green Dye]|r",
"",
"[|cFF33FFFF165-190|r]",
"Craft: 25x |cFFFFFFFF[Green Iron Bracers]|r",
"Requires: 150 |cFFFFFFFF[Iron Bar]|r, 25 |cFFFFFFFF[Green Dye]|r",
"",
"[|cFF33FFFF190-200|r]",
"Craft: 10x |cFFFFFFFF[Golden Scale Bracers]|r",
"Requires: 50 |cFFFFFFFF[Steel Bar]|r, 20 |cFFFFFFFF[Heavy Grinding Stone]|r",
"",
"[|cFF33FFFF200-210|r]",
"Craft: 30x |cFFFFFFFF[Solid Grinding Stone]|r",
"Requires: 120 |cFFFFFFFF[Solid Stone]|r",
"",
"[|cFF33FFFF210-225|r]",
"Craft: 15x |cFFFFFFFF[Heavy Mithril Gauntlet]|r",
"Requires: 90 |cFFFFFFFF[Mithril Bar]|r, 60 |cFFFFFFFF[Mageweave Cloth]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Artisan Blacksmith]|r (Requires Character Level 35; Raises Cap [225] > [300])",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Brikk Keencraft]|r / |cFF33FF99[Booty Bay, Stranglethorn Vale]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF225 - 235|r]",
"------------------------------------------------------------------------------------------------",
"Craft: 10x |cFFFFFFFF[Steel Plate Helm]|r",
"Requires: 140 |cFFFFFFFF[Steel Bar]|r, 10 |cFFFFFFFF[Solid Grinding Stone]|r",
"|cFFFF0000[H]|r Players: Keep 4 |cFFFFFFFF[Steel Plate Helm]|r for Armorsmithing Specialization",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF235 - 250|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Plans: Mithril Spurs]|r",
"WHERE:",
"      |cFFFFFF00[Auction House]|r Usually expensive purchase",
"      |cFF0070DD[World Drop <1%]|r",
"",
"      NOTE: This is the best recipe for [|cFF33FFFF235-270|r], but difficult to acquire.",
"      You can use the |cFFB2FF66Alternative Recipes|r, they are just less efficient.",
"------------------------------------------------------------------------------------------------",
"Craft: 20x |cFFFFFFFF[Mithril Spurs]|r",
"Requires: 80 |cFFFFFFFF[Mithril Bar]|r, 60 |cFFFFFFFF[Solid Grinding Stone]|r",
"",
"      |cFFB2FF66Alternative Recipes|r:",
"      Craft: 15x |cFFFFFFFF[Mithril Coif]|r",
"      Requires: 150 |cFFFFFFFF[Mithril Bar]|r, 90 |cFFFFFFFF[Mageweave Cloth]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF250 - 260|r]",
"------------------------------------------------------------------------------------------------",
"Craft: 20x |cFFFFFFFF[Dense Sharpening Stone]|r",
"Requires: 20 |cFFFFFFFF[Dense Stone]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF260 - 270|r]",
"------------------------------------------------------------------------------------------------",
"Craft: 20x |cFFFFFFFF[Mithril Spurs]|r",
"Requires: 80 |cFFFFFFFF[Mithril Bar]|r, 60 |cFFFFFFFF[Solid Grinding Stone]|r",
"",
"      |cFFB2FF66Alternative Recipes|r:", 
"      |cFF1EFF00[Plans: Thorium Bracers]|r, |cFF1EFF00[Plans: Thorium Belt]|r, or |cFF1EFF00[Plans: Radiant Belt]|r",
"",
"      Craft: 10x |cFFFFFFFF[Thorium Bracers]|r",
"      Requires: 120 |cFFFFFFFF[Thorium Bar]|r, 40 |cFFFFFFFF[Blue Power Crystal]|r",
"      or",
"      Craft: 10x |cFFFFFFFF[Thorium Belt]|r",
"      Requires: 120 |cFFFFFFFF[Thorium Bar]|r, 40 |cFFFFFFFF[Red Power Crystal]|r",
"      or",
"      Craft: 10x |cFFFFFFFF[Radiant Belt]|r",
"      Requires: 100 |cFFFFFFFF[Thorium Bar]|r, 20 |cFFFFFFFF[Heart of Fire]|r",
"      or",
"      NOTE: If unable to obtain any of the above Plans, see |cFF1EFF00[Imperial Plate]|r below",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Plans: Imperial Plate Belt]|r",
"      |cFF1EFF00[Plans: Imperial Plate Bracers]|r",
"      |cFF1EFF00[Plans: Imperial Plate Boots]|r",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Derotain Mudsipper]|r / |cFF33FF99[Gadgetzan, Tanaris]|r: |cFFFFD700[! A Blue Light Bargain]|r chain",
"",
"      (Requires Character Level 50; Blacksmithing 265, 40 |cFFFFFFFF[Thorium Bar]|r",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF260-265|r]",
"Craft: 8x |cFFFFFFFF[Heavy Mithril Boots]|r",
"Requires: 112 |cFFFFFFFF[Mithril Bar]|r, 32 |cFFFFFFFF[Thick Leather]|r",
"",
"[|cFF33FFFF265-270|r]",
"Craft: 5x |cFFFFFFFF[Imperial Plate Belt]|r",
"Requires: 110 |cFFFFFFFF[Thorium Bar]|r, 30 |cFFFFFFFF[Rugged Leather]|r, 5 |cFF00FF00[Aquamarine]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF270 - 295|r]",
"------------------------------------------------------------------------------------------------",
"Craft: 25x |cFFFFFFFF[Imperial Plate Bracers]|r",
"Requires: 250 |cFFFFFFFF[Thorium Bar]|r, 25 |cFF00FF00[Star Ruby]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF295 - 300|r]",
"------------------------------------------------------------------------------------------------",
"Craft: 5x |cFFFFFFFF[Imperial Plate Boots]|r",
"Requires: 170 |cFFFFFFFF[Thorium Bar]|r, 5 |cFF00FF00[Star Ruby]|r, 5 |cFF00FF00[Aquamarine]|r"
	}
}