Cooking = {
    buttonText = "Cooking",
    headerText = "THE COOK",
    content = {
"------------------------------------------------------------------------------------------------",
"MATERIAL LIST",
"------------------------------------------------------------------------------------------------",
"52 |cFFFFFFFF[Raw Brilliant Smallfish]|r",
"55 |cFFFFFFFF[Raw Longjaw Mud Snapper]|r",
"120 |cFFFFFFFF[Raw Bristle Whisker Catfish]|r",
"55 |cFFFFFFFF[Raw Mithril Head Trout]|r",
"",
"Skill 225 and up (untested):",
"140 |cFFFFFFFF[Zesty Clam Meat]|r",
"65 |cFF9D9D9D[Ice Cold Milk]|r",
"77 |cFFFFFFFF[Giant Egg]|r",
"20 |cFFFFFFFF[Alterac Swiss]|r",
"65 |cFFFFFFFF[Raw Spotted Yellowtail]|r",
"35 |cFFFFFFFF[Raw Sunscale Salmon]|r",
"35 |cFFFFFFFF[Raw Nightfin Snapper]|r",
"",
"------------------------------------------------------------------------------------------------",
"PREFACE",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"Some |cFF1EFF00Recipes|r may require completing |cFFFFD700[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the |cFFFFFF00[Auction House]|r",
"",
"NOTE: The 1-225 route is fish only, verified against Wowhead.",
"No spices are needed. Everything above 225 is untested.",
"",
"------------------------------------------------------------------------------------------------",
"LEVELING COOKING",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF1 - 50|r]",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"[|cFF33FFFF1-50|r]",
"Craft: 52x |cFFFFFFFF[Brilliant Smallfish]|r",
"Requires: 52 |cFFFFFFFF[Raw Brilliant Smallfish]|r",
"Recipe, if you do not have it yet:",
"      |cFFFF0000[H]|r |cFF33FF99[Sewa Mistrunner]|r / |cFF33FF99[Thunder Bluff, Mulgore]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Catherine Leland]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Journeyman Cook]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF50 - 100|r]",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"[|cFF33FFFF50-100|r]",
"Craft: 55x |cFFFFFFFF[Longjaw Mud Snapper]|r",
"Requires: 55 |cFFFFFFFF[Raw Longjaw Mud Snapper]|r",
"Recipe, if you do not have it yet:",
"      |cFFFF0000[H]|r |cFF33FF99[Naal Mistrunner]|r / |cFF33FF99[Thunder Bluff, Mulgore]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Tharynn Bouden]|r / |cFF33FF99[Goldshire, Elwynn Forest]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF100 - 150|r]",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"[|cFF33FFFF100-150|r]",
"Craft: 55x |cFFFFFFFF[Bristle Whisker Catfish]|r",
"Requires: 55 |cFFFFFFFF[Raw Bristle Whisker Catfish]|r",
"Recipe, if you do not have it yet:",
"      |cFFFF0000[H]|r |cFF33FF99[Naal Mistrunner]|r / |cFF33FF99[Thunder Bluff, Mulgore]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Catherine Leland]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Expert Cookbook]|r (Requires Character Level 20; Raises Cap [150] > [225])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Wulan]|r / |cFF33FF99[Shadowprey Village, Desolace]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Shandrina]|r / |cFF33FF99[Silverwind Refuge, Ashenvale]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF150 - 175|r]",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"[|cFF33FFFF150-175|r]",
"Craft: 65x |cFFFFFFFF[Bristle Whisker Catfish]|r",
"Requires: 65 |cFFFFFFFF[Raw Bristle Whisker Catfish]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF175 - 225|r]",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"[|cFF33FFFF175-225|r]",
"Craft: 55x |cFFFFFFFF[Mithril Headed Trout]|r",
"Requires: 55 |cFFFFFFFF[Raw Mithril Head Trout]|r",
"Recipe, if you do not have it yet:",
"      |cFFFF0000[H]|r |cFF33FF99[Shankys]|r / |cFF33FF99[Orgrimmar, Durotar]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Tansy Puddlefizz]|r / |cFF33FF99[Ironforge, Dun Morogh]|r",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Artisan Cook]|r (Requires Character Level 35; Raises Cap [225] > [300])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Zamja]|r / |cFF33FF99[Orgrimmar, Durotar]|r: |cFFFFD700[! To Gadgetzan You Go!]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Daryl Riknussun]|r / |cFF33FF99[Ironforge, Dun Morogh]|r: |cFFFFD700[! I Know A Guy]|r",
"",
"      Both quests will lead to:",
"      |cFFFFD700[N]|r |cFF33FF99[Dirge Quikcleave]|r / |cFF33FF99[Gadgetzan, Tanaris]|r: |cFFFFD700[! Clamlette Surprise]|r",
"      Requires: 12 |cFFFFFFFF[Giant Egg]|r, 10 |cFFFFFFFF[Zesty Clam Meat]|r, 20 |cFFFFFFFF[Alterac Swiss]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF225 - 275|r]",
"------------------------------------------------------------------------------------------------",
"|cFFFF8000UNVERIFIED: Vanilla WoW data, not checked for Forever|r",
"NOTE: Untested in the Forever beta. Verify these steps in game.",
"[|cFF33FFFF225-275|r]",
"Cook around 65 items from the recipes below.",
"",
"      |cFFFFFFFF[Undermine Clam Chowder]|r",
"      Ingredients: 130 |cFFFFFFFF[Zesty Clam Meat]|r, 65 |cFF9D9D9D[Ice Cold Milk]|r",
"      Source: |cFFFFD700[N]|r |cFF33FF99[Jabbey]|r / |cFF33FF99[Steamwheedle Port, Tanaris]|r",
"",
"      |cFFFFFFFF[Spotted Yellowtail]|r",
"      Ingredients: 65 |cFFFFFFFF[Raw Spotted Yellowtail]|r",
"      Source: |cFFFFD700[N]|r |cFF33FF99[Gikkix]|r / |cFF33FF99[Steamwheedle Port, Tanaris]|r",
"",
"      |cFFFFFFFF[Monster Omelet]|r",
"      Ingredients: 65 |cFFFFFFFF[Giant Egg]|r",
"      Source: |cFFFFD700[N]|r |cFF33FF99[Himmik]|r / |cFF33FF99[Winterspring, Everlook]|r",
"",
"      |cFFFFFFFF[Tender Wolf Steak]|r",
"      Ingredients: 65 |cFFFFFFFF[Tender Wolf Meat]|r",
"      Source: |cFFFFD700[N]|r |cFF33FF99[Dirge Quikcleave]|r / |cFF33FF99[Gadgetzan, Tanaris]|r",
"",
"      |cFFFFFFFF[Filet of Redgill]|r",
"      Ingredients: 65 |cFFFFFFFF[Raw Redgill]|r",
"      Source: |cFFFFD700[N]|r |cFF33FF99[Kelsey Yance]|r / |cFF33FF99[Booty Bay, Stranglethorn Vale]|r",
"",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF275 - 300|r]",
"------------------------------------------------------------------------------------------------",
"|cFFFF8000UNVERIFIED: Vanilla WoW data, not checked for Forever|r",
"Craft: 35x |cFFFFFFFF[Poached Sunscale Salmon]|r",
"Ingredients: 35 |cFFFFFFFF[Raw Sunscale Salmon]|r",
"",
"OR",
"",
"Craft: 35x |cFFFFFFFF[Nightfin Soup]|r",
"Ingredients: 35 |cFFFFFFFF[Raw Nightfin Snapper]|r",
"",
"Source: (Both) |cFFFFD700[N]|r |cFF33FF99[Gikkix]|r / |cFF33FF99[Steamwheedle Port, Tanaris]|r"
    }
}