Cooking = {
    buttonText = "Cooking",
    headerText = "THE COOK",    
    content = {
"------------------------------------------------------------------------------------------------",
"MATERIAL LIST",
"------------------------------------------------------------------------------------------------",
"55 |cFFFFFFFF[Stringy Wolf Meat]|r",
"55 |cFFFFFFFF[Chunk of Boar Meat]|r",
"55 |cFFFFFFFF[Raw Brilliant Smallfish]|r",
"75 |cFFFFFFFF[Bear Meat]|r",
"55 |cFFFFFFFF[Clam Meat]|r",
"55 |cFF9D9D9D[Refreshing Spring Water]|r",
"55 |cFFFFFFFF[Raw Longjaw Mud Snapper]|r",
"40 |cFFFFFFFF[Crawler Meat]|r",
"40 |cFFFFFFFF[Boar Ribs]|r",
"40 |cFFFFFFFF[Raw Bristle Whisker Catfish]|r",
"50 |cFFFFFFFF[Raptor Egg]|r",
"50 |cFFFFFFFF[Raptor Flesh]|r",
"140 |cFFFFFFFF[Zesty Clam Meat]|r",
"65 |cFF9D9D9D[Ice Cold Milk]|r",
"77 |cFFFFFFFF[Giant Egg]|r",
"65 |cFFFFFFFF[Raw Spotted Yellowtail]|r",
"35 |cFFFFFFFF[Raw Sunscale Salmon]|r",
"35 |cFFFFFFFF[Raw Nightfin Snapper]|r",
"",
"------------------------------------------------------------------------------------------------",
"PREFACE",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"Some |cFF1EFF00Recipes|r may require completing |cFFFFD700[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the |cFFFFFF00[Auction House]|r",
"",
"------------------------------------------------------------------------------------------------",
"LEVELING COOKING",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF1 - 50|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF1-50|r]",
"Cook around 55 from the recipes below.",
"",
"      |cFFFFFFFF[Charred Wolf Meat]|r",
"      Ingredients: |cFFFFFFFF[Stringy Wolf Meat]|r",
"      Source: |cFF33FF99[Cooking Trainer]|r",
"",
"      |cFFFFFFFF[Roasted Boar Meat]|r",
"      Ingredients: |cFFFFFFFF[Chunk of Boar Meat]|r",
"      Source: |cFF33FF99[Cooking Trainer]|r",
"",
"      |cFFFFFFFF[Brilliant Smallfish]|r",
"      Ingredients: |cFFFFFFFF[Raw Brilliant Smallfish]|r",
"      Source: |cFF33FF99[Fishing Vendor]|r",
"",
"      |cFFFFFFFF[Slitherskin Mackerel]|r",
"      Ingredients: |cFFFFFFFF[Slitherskin Mackerel]|r",
"      Source: |cFF33FF99[Fishing Vendor]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Journeyman Cook]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF50 - 100|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF50-100|r]",
"Cook around 55 items from the recipes below.",
"",
"      |cFFFFFFFF[Smoked Bear Meat]|r",
"      Ingredients: |cFFFFFFFF[Bear Meat]|r",
"      Source:",
"      |cFFFF0000[H]|r |cFF33FF99[Andrew Hilbert]|r / |cFF33FF99[Sepulcher, Silverpine Forest]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Drac Roughcut]|r / |cFF33FF99[Thelsamar, Loch Modan]|r",
"",
"      |cFFFFFFFF[Boiled Clams]|r",
"      Ingredients: |cFFFFFFFF[Clam Meat]|r, |cFF9D9D9D[Refreshing Spring Water]|r",
"      Source: |cFF33FF99[Cooking Trainer]|r",
"",
"      |cFFFFFFFF[Coyote Steak]|r",
"      Ingredients: |cFFFFFFFF[Coyote Meat]|r",
"      Source: |cFF33FF99[Cooking Trainer]|r",
"",
"      |cFFFFFFFF[Longjaw Mud Snapper]|r",
"      Ingredients: |cFFFFFFFF[Raw Longjaw Mud Snapper]|r",
"      Source: |cFF33FF99[Fishing Vendor]|r",
"",
"      |cFFFFFFFF[Rainbow Fin Albacore]|r",
"      Ingredients: |cFFFFFFFF[Raw Rainbow Fin Albacore]|r",
"      Source: |cFF33FF99[Fishing Vendor]|r",
"",
"      |cFFFFFFFF[Strider Stew]|r",
"      Ingredients: |cFFFFFFFF[Strider Meat]|r, |cFFFFFFFF[Shiny Red Apple]|r",
"      Source:",
"      |cFFFF0000[H]|r |cFF33FF99[Tari'qa]|r / |cFF33FF99[Crossroads, The Barrens]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Alanndarian Nightsong]|r / |cFF33FF99[Auberdine, Darkshore]|r: |cFFFFD700[! Easy Strider Living]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF100 - 130|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF100-130|r]",
"Cook around [|cFF33FFFF30-40|r] items from the recipes below.",
"",
"      |cFFFFFFFF[Crab Cake]|r",
"      Ingredients: |cFFFFFFFF[Crawler Meat]|r",
"      Source: |cFF33FF99[Cooking Trainer]|r",
"",
"      |cFFFFFFFF[Dry Pork Ribs]|r",
"      Ingredients: |cFFFFFFFF[Boar Ribs]|r",
"      Source: |cFF33FF99[Cooking Trainer]|r",
"",
"      |cFFFFFFFF[Bristle Whisker Catfish]|r",
"      Ingredients: |cFFFFFFFF[Raw Bristle Whisker Catfish]|r",
"      Source: |cFF33FF99[Fishing Vendor]|r",
"",
"      |cFF66B2FF[A]|r |cFFFFFFFF[Cooked Crab Claw]|r",
"      Ingredients: |cFFFFFFFF[Crawler Claw]|r",
"      Source: |cFF66B2FF[A]|r |cFF33FF99[Kendor Kabonka]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Expert Cookbook]|r (Requires Character Level 20; Raises Cap [150] > [225])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Wulan]|r / |cFF33FF99[Shadowprey Village, Desolace]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Shandrina]|r / |cFF33FF99[Silverwind Refuge, Ashenvale]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF130 - 175|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Recipe: Curiously Tasty Omelet]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Keena]|r / |cFF33FF99[Hammerfall, Arathi Highlands]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Kendor Kabonka]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF130-175|r]",
"Craft: 50x |cFFFFFFFF[Curiously Tasty Omelet]|r",
"Requires: 50 |cFFFFFFFF[Raptor Egg]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF175 - 225|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Recipe: Roast Raptor]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Keena]|r / |cFF33FF99[Hammerfall, Arathi Highlands]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Hammon Karwn]|r / |cFF33FF99[Refuge Point, Arathi Highlands]|r",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF175-225|r]",
"Craft: 50x |cFFFFFFFF[Roast Raptor]|r",
"Ingredients: 50 |cFFFFFFFF[Raptor Flesh]|r",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Artisan Cook]|r (Requires Character Level 35; Raises Cap [225] > [300])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Zamja]|r / |cFF33FF99[Orgrimmar, Durator]|r: |cFFFFD700[! To Gadgetzan You Go!]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Daryl Riknussun]|r / |cFF33FF99[Ironforge, Dun Morogh]|r: |cFFFFD700[! I Know A Guy]|r",
"",
"      Both quests will lead to:",
"      |cFFFFD700[N]|r |cFF33FF99[Dirge Quikcleave]|r / |cFF33FF99[Gadgetzan, Tanaris]|r: |cFFFFD700[! Clamlette Surprise]|r", 
"      Requires: 12 |cFFFFFFFF[Giant Egg]|r, 10 |cFFFFFFFF[Zesty Clam Meat]|r, 20 |cFFFFFFFF[Alterac Swiss]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF225 - 275|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF225-275|r]",
"Cook around 65 items from the recipes below.",
"",
"      |cFFFFFFFF[Undermine Clam Chowder]|r",
"      Ingredients: 130 |cFFFFFFFF[Zesty Clam Meat]|r, 65 |cFF9D9D9D[Ice Cold Milk]|r",
"      Source: |cFFFFD700[N]|r |cFF33FF99[Jabbey]|r / |cFF33FF99[Steamwheedle Port, Tanaris]|r",
"",
"      |cFFFFFFFF[Spotted Yellowtail]|r",
"      Ingredients: 65 |cFFFFFFFF[Raw Spotted Yellowtail]|r",
"      Source: |cFFFFD700[N]|r |cFF33FF99[Gikkix]|r / |cFF33FF99[Steamwheedle Port, Tanaris]|r",
"",
"      |cFFFFFFFF[Monster Omelet]|r",
"      Ingredients: 65 |cFFFFFFFF[Giant Egg]|r",
"      Source: |cFFFFD700[N]|r |cFF33FF99[Himmik]|r / |cFF33FF99[Winterspring, Everlook]|r",
"",
"      |cFFFFFFFF[Tender Wolf Steak]|r",
"      Ingredients: 65 |cFFFFFFFF[Tender Wolf Meat]|r",
"      Source: |cFFFFD700[N]|r |cFF33FF99[Dirge Quikcleave]|r / |cFF33FF99[Gadgetzan, Tanaris]|r",
"",
"      |cFFFFFFFF[Filet of Redgill]|r",
"      Ingredients: 65 |cFFFFFFFF[Raw Redgill]|r",
"      Source: |cFFFFD700[N]|r |cFF33FF99[Kelsey Yance]|r / |cFF33FF99[Booty Bay, Stranglethorn Vale]|r",
"",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF275 - 300|r]",
"------------------------------------------------------------------------------------------------",
"Craft: 35x |cFFFFFFFF[Poached Sunscale Salmon]|r",
"Ingredients: 35 |cFFFFFFFF[Raw Sunscale Salmon]|r",
"",
"OR",
"",
"Craft: 35x |cFFFFFFFF[Nightfin Soup]|r",
"Ingredients: 35 |cFFFFFFFF[Raw Nightfin Snapper]|r",
"",
"Source: (Both) |cFFFFD700[N]|r |cFF33FF99[Gikkix]|r / |cFF33FF99[Steamwheedle Port, Tanaris]|r"
    }
}