Enchanting = {
buttonText = "Enchanting",
headerText = "THE ENCHANTER",
content = {
"------------------------------------------------------------------------------------------------",
"MATERIAL LIST",
"------------------------------------------------------------------------------------------------",
"125 |cFFFFFFFF[Strange Dust]|r",
"1 |cFF1EFF00[Lesser Magic Essence]|r",
"12 |cFF1EFF00[Greater Magic Essence]|r",
"25 |cFF1EFF00[Lesser Astral Essence]|r",
"130 |cFFFFFFFF[Soul Dust]|r",
"2 |cFF1EFF00[Greater Astral Essence]|r",
"250 |cFFFFFFFF[Vision Dust]|r",
"2 |cFF1EFF00[Greater Mystic Essence]|r",
"5 |cFF1EFF00[Lesser Nether Essence]|r",
"360 |cFFFFFFFF[Dream Dust]|r",
"40 |cFFFFFFFF[Purple Lotus]|r",
"40 |cFFFFFFFF[Illusion Dust]|r",
"4 |cFF1EFF00[Greater Eternal Essence]|r",
"4 |cFF0070DD[Small Brilliant Shard]|r",
"2 |cFF0070DD[Large Brilliant Shard]|r",
"1 |cFFFFFFFF[Silver Rod]|r",
"1 |cFF1EFF00[Shadowgem]|r",
"1 |cFFFFFFFF[Golden Rod]|r",
"1 |cFF1EFF00[Iridescent Pearl]|r",
"1 |cFFFFFFFF[Truesilver Rod]|r",
"1 |cFF1EFF00[Black Pearl]|r",
"1 |cFFFFFFFF[Arcanite Rod]|r",
"1 |cFF1EFF00[Golden Pearl]|r",
"",
"------------------------------------------------------------------------------------------------",
"PREFACE",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"Some |cFF1EFF00Formulas|r may require completing |cFFFFD700[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the |cFFFFFF00[Auction House]|r",
"",
"Unenchanted |cFFFFFFFF[Rods]|r are created by |cFF33FF99Blacksmithing|r and purchased from vendors",
"",
"------------------------------------------------------------------------------------------------",
"LEVELING ENCHANTING",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF1 - 50|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF1-2|r]",
"Craft: 1x |cFFFFFFFF[Runed Copper Rod]|r",
"Requires: 1 |cFFFFFFFF[Copper Rod]|r, 1 |cFFFFFFFF[Strange Dust]|r, 1 |cFF1EFF00[Lesser Magic Essence]|r",
"NOTE: |cFFFFFFFF[Copper Rod]|r is sold by Trade Goods, Trade Supplies, and Enchanting Supplies vendors",
"",
"[|cFF33FFFF2-50|r]",
"Craft: 48x |cFFFFFFFF[Enchant Bracer - Minor Health]|r",
"Requires: 48 |cFFFFFFFF[Strange Dust]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Journeyman Enchanter]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Godan]|r / |cFF33FF99[Orgrimmar, Durotar]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Lavinia Crowe]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Teg Dawnstrider]|r / |cFF33FF99[Thunder Bluff, Mulgore]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Gimble Thistlefuzz]|r / |cFF33FF99[Ironforge, Dun Morogh]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Lucan Cordell]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Taladan]|r / |cFF33FF99[Darnassus, Teldrassil]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF50 - 110|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF50-90|r]",
"Craft: 40x |cFFFFFFFF[Enchant Bracer - Minor Health]|r",
"Requires: 40 |cFFFFFFFF[Strange Dust]|r",
"NOTE: If |cFFFFFFFF[Strange Dust]|r is cheap and |cFF1EFF00[Greater Magic Essence]|r is expensive, make up to 120",
"",
"[|cFF33FFFF90-100|r]",
"Craft: 10x |cFFFFFFFF[Enchant Bracer - Minor Stamina]|r",
"Requires: 30 |cFFFFFFFF[Strange Dust]|r",
"",
"[|cFF33FFFF100-101|r]",
"Craft: 1x |cFFFFFFFF[Runed Silver Rod]|r",
"Requires: 1 |cFFFFFFFF[Silver Rod]|r, 6 |cFFFFFFFF[Strange Dust]|r, 3 |cFF1EFF00[Greater Magic Essence]|r, 1 |cFF1EFF00[Shadowgem]|r",
"",
"[|cFF33FFFF101-110|r]",
"Craft: 9x |cFFFFFFFF[Greater Magic Wand]|r",
"Requires: 9 |cFFFFFFFF[Simple Wood]|r, 9 |cFF1EFF00[Greater Magic Essence]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF110 - 135|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Formula: Enchant Bracer - Lesser Strength]|r |cFFFF8000[Limited supply]|r",
"      |cFF1EFF00[Formula: Enchant Cloak - Minor Agility]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Kulwia]|r / |cFF33FF99[Stonetalon Mountains]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Dalria]|r / |cFF33FF99[Astranaar, Ashenvale]|r",
"NOTE: Respawn timer is between 30-50 minutes",
"------------------------------------------------------------------------------------------------",
"Craft: 25x |cFFFFFFFF[Enchant Cloak - Minor Agility]|r",
"Requires: 25 |cFF1EFF00[Lesser Astral Essence]|r",
"",
"|cFFB2FF66Alternative Recipe|r:",
"      |cFFFFFFFF[Enchant 2H Weapon - Minor Impact]|r",
"      Requires: |cFFFFFFFF[Strange Dust]|r, |cFFFFFFFF[Small Glimmering Shard]|r",
"      NOTE: Use if |cFFFFFFFF[Astral Essence]|r is expensive and |cFFFFFFFF[Small Glimmering Shard]|r is cheap",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Expert Enchanter]|r (Requires Character Level 20; Raises Cap [150] > [225])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Hgarth]|r / |cFF33FF99[Sun Rock Retreat, Stonetalon Mountains]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Kitta Firewind]|r / |cFF33FF99[Tower of Azora, Elwynn Forest]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF135 - 156|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF135-155|r]",
"Craft: 20x |cFFFFFFFF[Enchant Bracer - Lesser Stamina]|r",
"Requires: 40 |cFFFFFFFF[Soul Dust]|r",
"",
"[|cFF33FFFF155-156|r]",
"Craft: 1x |cFFFFFFFF[Runed Golden Rod]|r",
"Requires: 1 |cFFFFFFFF[Golden Rod]|r, 1 |cFF1EFF00[Iridescent Pearl]|r, 2 |cFF1EFF00[Greater Astral Essence]|r, 2 |cFFFFFFFF[Soul Dust]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF156 - 185|r]",
"------------------------------------------------------------------------------------------------",
"Craft: 40x |cFFFFFFFF[Enchant Bracer - Lesser Strength]|r",
"Requires: 80 |cFFFFFFFF[Soul Dust]|r",
"",
"|cFFB2FF66Alternative Recipe|r:",
"      |cFFFFFFFF[Enchant Bracer - Spirit]|r",
"      Requires: |cFFFFFFFF[Lesser Mystic Essence]|r",
"      NOTE: Switch at 165 if 1x |cFFFFFFFF[Lesser Mystic Essence]|r is cheaper than 2x |cFFFFFFFF[Soul Dust]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF185 - 225|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF185-200|r]",
"Craft: 15x |cFFFFFFFF[Enchant Bracer - Strength]|r",
"Requires: 15 |cFFFFFFFF[Vision Dust]|r",
"",
"[|cFF33FFFF200-201|r]",
"Craft: 1x |cFFFFFFFF[Runed Truesilver Rod]|r",
"Requires: 1 |cFFFFFFFF[Truesilver Rod]|r, 1 |cFF1EFF00[Black Pearl]|r, 2 |cFF1EFF00[Greater Mystic Essence]|r, 2 |cFFFFFFFF[Vision Dust]|r",
"",
"[|cFF33FFFF201-220|r]",
"Craft: 35x |cFFFFFFFF[Enchant Bracer - Strength]|r",
"Requires: 35 |cFFFFFFFF[Vision Dust]|r",
"NOTE: Recipe is yellow, may need to craft 30-35 times",
"",
"[|cFF33FFFF220-225|r]",
"Craft: 5x |cFFFFFFFF[Enchant Cloak - Greater Defense]|r",
"Requires: 15 |cFFFFFFFF[Vision Dust]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Artisan Enchanter]|r (Requires Character Level 35; Raises Cap [225] > [300])",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Annora]|r / |cFF33FF99[Uldaman, Badlands]|r",
"NOTE: Only spawns after killing all mobs in her area",
"NOTE: Bring 11.79 Gold to learn all recipes from Annora",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF225 - 250|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF225-230|r]",
"Craft: 5x |cFFFFFFFF[Enchant Gloves - Agility]|r",
"Requires: 5 |cFF1EFF00[Lesser Nether Essence]|r, 5 |cFFFFFFFF[Vision Dust]|r",
"",
"|cFFB2FF66Alternative Recipe|r:",
"      |cFFFFFFFF[Enchant Cloak - Greater Defense]|r",
"      NOTE: If you don't have |cFF1EFF00[Lesser Nether Essence]|r",
"",
"[|cFF33FFFF230-235|r]",
"Craft: 5x |cFFFFFFFF[Enchant Boots - Stamina]|r",
"Requires: 25 |cFFFFFFFF[Vision Dust]|r",
"",
"[|cFF33FFFF235-250|r]",
"Craft: 25x |cFFFFFFFF[Enchant Chest - Superior Health]|r",
"Requires: 150 |cFFFFFFFF[Vision Dust]|r",
"",
"NOTE: Learn everything from |cFF33FF99[Annora]|r before leaving Uldaman!",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF250 - 265|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Formula: Lesser Mana Oil]|r",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Kania]|r / |cFF33FF99[Silithus]|r (Upstairs in the Inn)",
"------------------------------------------------------------------------------------------------",
"Craft: 20x |cFFFFFFFF[Lesser Mana Oil]|r",
"Requires: 60 |cFFFFFFFF[Dream Dust]|r, 40 |cFFFFFFFF[Purple Lotus]|r, 20 |cFF9D9D9D[Crystal Vial]|r",
"NOTE: Can make up to 270 if |cFFFFFFFF[Purple Lotus]|r is cheap",
"",
"|cFFB2FF66Alternative Recipe|r:",
"      |cFFFFFFFF[Enchant Bracer - Greater Strength]|r",
"      Requires: |cFFFFFFFF[Dream Dust]|r, |cFFFFFFFF[Greater Nether Essence]|r",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Formula: Enchant Bracer - Greater Stamina]|r",
"WHERE:",
"      |cFFFFD700[Random World Drop]|r - Check |cFFFFFF00[Auction House]|r",
"NOTE: Best recipe to level from 245 to 265 or even 285",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF265 - 294|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Formula: Enchant Shield - Greater Stamina]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Daniel Bartlett]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Mythrin'dir]|r / |cFF33FF99[Darnassus, Teldrassil]|r",
"NOTE: Recipe binds when picked up! Don't buy with alt and try to mail it!",
"------------------------------------------------------------------------------------------------",
"Craft: 30x |cFFFFFFFF[Enchant Shield - Greater Stamina]|r",
"Requires: 300 |cFFFFFFFF[Dream Dust]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF294 - 295|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Formula: Runed Arcanite Rod]|r",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Lorelae Wintersong]|r / |cFF33FF99[Nighthaven, Moonglade]|r",
"------------------------------------------------------------------------------------------------",
"Craft: 1x |cFFFFFFFF[Runed Arcanite Rod]|r",
"Requires: 1 |cFFFFFFFF[Arcanite Rod]|r, 1 |cFF1EFF00[Golden Pearl]|r, 10 |cFFFFFFFF[Illusion Dust]|r, 4 |cFF1EFF00[Greater Eternal Essence]|r, 4 |cFF0070DD[Small Brilliant Shard]|r, 2 |cFF0070DD[Large Brilliant Shard]|r",
"",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFFLevels:|r] [|cFF33FFFF295 - 300|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Formula: Enchant Cloak - Superior Defense]|r",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Lorelae Wintersong]|r / |cFF33FF99[Nighthaven, Moonglade]|r",
"------------------------------------------------------------------------------------------------",
"Craft: 5x |cFFFFFFFF[Enchant Cloak - Superior Defense]|r",
"Requires: 40 |cFFFFFFFF[Illusion Dust]|r",
"",
"|cFFB2FF66Alternative Recipe|r:",
"      |cFFFFFFFF[Enchant Shield - Greater Stamina]|r",
"      NOTE: If you have a lot of |cFFFFFFFF[Dream Dust]|r or |cFFFFFFFF[Illusion Dust]|r is expensive"
}
}