Engineering = {
buttonText = "Engineering",
headerText = "THE ENGINEER",
content = {
"-------------------------------",
"Material List",
"-------------------------------",
"60 |cFFFFFFFF[Rough Stone]|r",
"66 |cFFFFFFFF[Copper Bar]|r",
"60 |cFFFFFFFF[Coarse Stone]|r",
"50 |cFFFFFFFF[Linen Cloth]|r",
"5 |cFF00FF00[Silver Bar]|r",
"110 |cFFFFFFFF[Bronze Bar]|r",
"30 |cFFFFFFFF[Heavy Stone]|r",
"10 |cFF00FF00[Moss Agate]|r",
"60 |cFFFFFFFF[Wool Cloth]|r",
"15 |cFFFFFFFF[Medium Leather]|r",
"4 |cFFFFFFFF[Steel Bar]|r",
"120 |cFFFFFFFF[Solid Stone]|r",
"170 |cFFFFFFFF[Mithril Bar]|r",
"20 |cFFFFFFFF[Mageweave Cloth]|r",
"60 |cFFFFFFFF[Dense Stone]|r",
"225 |cFFFFFFFF[Thorium Bar]|r",
"35 |cFFFFFFFF[Runecloth]|r",
"",
"-------------------------------------------------------------------------------------------",
"Preface",
"-------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r : Friendly with Horde",
"|cFF33FF99[A]|r : Friendly with Alliance",
"|cFFFFD700[N]|r : Neutral",
"",
"Buy |cFF9D9D9D[Blacksmith Hammer]|r from vendor near your trainer",
"Gnome characters get +15 Engineering skill from racial bonus",
"Pair with Mining to save gold on materials",
"",
"Some |cFF1EFF00Recipes|r may require completing |cFFFFFF00[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the [Auction House]",
"",
"-------------------------------",
"LEVELING ENGINEERING",
"-------------------------------",
"-------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF1 - 75|r]",
"-------------------------------",
"[|cFF33FFFF1-30|r]",
"Craft: 60x |cFFFFFFFF[Rough Blasting Powder]|r",
"Requires: 60 |cFFFFFFFF[Rough Stone]|r",
"NOTE: Save these for later use. May reach 40 with this recipe",
"",
"[|cFF33FFFF30-50|r]",
"Craft: 30x |cFFFFFFFF[Handful of Copper Bolts]|r",
"Requires: 30 |cFFFFFFFF[Copper Bar]|r",
"NOTE: Save these for later use",
"",
"[|cFF33FFFF50-51|r]",
"Craft: 1x |cFFFFFFFF[Arclight Spanner]|r",
"Requires: 6 |cFFFFFFFF[Copper Bar]|r",
"NOTE: Keep this tool, required for crafting other recipes",
"",
"[|cFF33FFFF51-75|r]",
"Craft: 30x |cFFFFFFFF[Rough Copper Bomb]|r",
"Requires: 30 |cFFFFFFFF[Copper Bar]|r, 30 |cFFFFFFFF[Handful of Copper Bolts]|r, 60 |cFFFFFFFF[Rough Blasting Powder]|r, 30 |cFFFFFFFF[Linen Cloth]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFFFFFFFF[Journeyman Engineer]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Franklin Lloyd]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Nogg]|r / |cFF33FF99[Orgrimmar, Durator]|r",
"",
"      |cFF33FF99[A]|r |cFF33FF99[Trixie Quikswitch]|r / |cFF33FF99[Ironforge, Dun Morogh]|r",
"      |cFF33FF99[A]|r |cFF33FF99[Lilliam Sparkspindle]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"------------------------------------------------------------------------------------------------",
"",
"-------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF75 - 135|r]",
"-------------------------------",
"[|cFF33FFFF75-90|r]",
"Craft: 60x |cFFFFFFFF[Coarse Blasting Powder]|r",
"Requires: 60 |cFFFFFFFF[Coarse Stone]|r",
"NOTE: Save these for later use",
"",
"[|cFF33FFFF90-100|r]",
"Craft: 20x |cFFFFFFFF[Coarse Dynamite]|r",
"Requires: 60 |cFFFFFFFF[Coarse Blasting Powder]|r, 20 |cFFFFFFFF[Linen Cloth]|r",
"",
"[|cFF33FFFF100-105|r]",
"Craft: 5x |cFFFFFFFF[Silver Contact]|r",
"Requires: 5 |cFF00FF00[Silver Bar]|r",
"",
"Alternative if Silver Bar is expensive:",
"Craft: 5x |cFFFFFFFF[Flying Tiger Goggles]|r",
"Requires: 30 |cFFFFFFFF[Light Leather]|r, 10 |cFF00FF00[Tigerseye]|r",
"",
"[|cFF33FFFF105-125|r]",
"Craft: 25x |cFFFFFFFF[Bronze Tube]|r",
"Requires: 50 |cFFFFFFFF[Bronze Bar]|r, 25 |cFF9D9D9D[Weak Flux]|r",
"NOTE: Weak Flux sold by Engineering Supply vendors near your trainer",
"",
"[|cFF33FFFF125-135|r]",
"Craft: 10x |cFFFFFFFF[Standard Scope]|r",
"Requires: 10 |cFFFFFFFF[Bronze Tube]|r, 10 |cFF00FF00[Moss Agate]|r",
"NOTE: Start making Heavy Blasting Powder if Moss Agate is too expensive",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFFFFFFFF[Expert Engineer]|r (Requires Character Level 20; Raises Cap [150] > [225])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Roxxik]|r / |cFF33FF99[Orgrimmar, Durator]|r",
"",
"      |cFF33FF99[A]|r |cFF33FF99[Springspindle Fizzlegear]|r / |cFF33FF99[Ironforge, Dun Morogh]|r",
"------------------------------------------------------------------------------------------------",
"",
"-------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF135 - 200|r]",
"-------------------------------",
"[|cFF33FFFF135-150|r]",
"Craft: 30x |cFFFFFFFF[Heavy Blasting Powder]|r",
"Requires: 30 |cFFFFFFFF[Heavy Stone]|r",
"NOTE: Save these for later",
"",
"Craft: 15x |cFFFFFFFF[Whirring Bronze Gizmo]|r",
"Requires: 30 |cFFFFFFFF[Bronze Bar]|r, 15 |cFFFFFFFF[Wool Cloth]|r",
"NOTE: Save these for later",
"",
"[|cFF33FFFF150-160|r]",
"Craft: 15x |cFFFFFFFF[Bronze Framework]|r",
"Requires: 30 |cFFFFFFFF[Bronze Bar]|r, 15 |cFFFFFFFF[Medium Leather]|r, 15 |cFFFFFFFF[Wool Cloth]|r",
"NOTE: Save these. May reach 160, stop and continue next step",
"",
"[|cFF33FFFF160-175|r]",
"Craft: 15x |cFFFFFFFF[Explosive Sheep]|r",
"Requires: 30 |cFFFFFFFF[Heavy Blasting Powder]|r, 15 |cFFFFFFFF[Whirring Bronze Gizmo]|r, 15 |cFFFFFFFF[Bronze Framework]|r, 30 |cFFFFFFFF[Wool Cloth]|r",
"NOTE: Keep 5 if you choose Goblin Engineering at 200",
"",
"[|cFF33FFFF175-194|r]",
"Craft: 60x |cFFFFFFFF[Solid Blasting Powder]|r",
"Requires: 120 |cFFFFFFFF[Solid Stone]|r",
"NOTE: Save these for later use",
"",
"[|cFF33FFFF194-195|r]",
"Craft: 1x |cFFFFFFFF[Gyromatic Micro-Adjustor]|r",
"Requires: 4 |cFFFFFFFF[Steel Bar]|r",
"NOTE: Keep this, required for some Engineering recipes",
"",
"[|cFF33FFFF195-200|r]",
"Craft: 7x |cFFFFFFFF[Mithril Tube]|r",
"Requires: 21 |cFFFFFFFF[Mithril Bar]|r",
"NOTE: Stop at 200. Keep 6 if you choose Gnomish Engineering",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFFFFFFFF[Artisan Engineer]|r (Requires Character Level 35; Raises Cap [225] > [300])", 
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Buzzek Bracketswing]|r / |cFF33FF99[Gadgetzan, Tanaris]|r",
"------------------------------------------------------------------------------------------------",
"",
"-------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF200 - 260|r]",
"-------------------------------",
"[|cFF33FFFF200-215|r]",
"Craft: 20x |cFFFFFFFF[Unstable Trigger]|r",
"Requires: 20 |cFFFFFFFF[Mithril Bar]|r, 20 |cFFFFFFFF[Mageweave Cloth]|r, 20 |cFFFFFFFF[Solid Blasting Powder]|r",
"NOTE: Save these for later",
"",
"[|cFF33FFFF215-238|r]",
"Craft: 40x |cFFFFFFFF[Mithril Casing]|r",
"Requires: 120 |cFFFFFFFF[Mithril Bar]|r",
"NOTE: Save these for later",
"",
"[|cFF33FFFF238-250|r]",
"Craft: 20x |cFFFFFFFF[Hi-Explosive Bomb]|r",
"Requires: 40 |cFFFFFFFF[Mithril Casing]|r, 20 |cFFFFFFFF[Unstable Trigger]|r, 40 |cFFFFFFFF[Solid Blasting Powder]|r",
"",
"[|cFF33FFFF250-260|r]",
"Craft: 30x |cFFFFFFFF[Dense Blasting Powder]|r",
"Requires: 60 |cFFFFFFFF[Dense Stone]|r",
"NOTE: May need more than 30 to reach 260",
"",
"-------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF260 - 300|r]",
"-------------------------------",
"-------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Schematic: Thorium Widget]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Sovik]|r / |cFF33FF99[Orgrimmar]|r",
"",
"      |cFF33FF99[A]|r |cFF33FF99[Gearcutter Cogspinner]|r / |cFF33FF99[Ironforge]|r",
"-------------------------------------------------------------------------------------------",
"[|cFF33FFFF260-285|r]",
"Craft: 35x |cFFFFFFFF[Thorium Widget]|r",
"Requires: 105 |cFFFFFFFF[Thorium Bar]|r, 35 |cFFFFFFFF[Runecloth]|r",
"NOTE: Yellow craft for last few points, may not reach 285",
"",
"-------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Schematic: Thorium Tube]|r",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Xizzer Fizzbolt]|r / |cFF33FF99[Everlook, Winterspring]|r",
"-------------------------------------------------------------------------------------------",
"",
"[|cFF33FFFF285-300|r]",
"Craft: 20x |cFFFFFFFF[Thorium Tube]|r",
"Requires: 120 |cFFFFFFFF[Thorium Bar]|r"
}
}