FirstAid = {
  buttonText = "First Aid",
  headerText = "THE FIRST AIDER",
  content = {
"------------------------------------------------------------------------------------------------",
"Material List",
"------------------------------------------------------------------------------------------------",
"170 |cFFFFFFFF[Linen Cloth]|r",
"180 |cFFFFFFFF[Wool Cloth]|r",
"150 |cFFFFFFFF[Silk Cloth]|r",
"120 |cFFFFFFFF[Mageweave Cloth]|r",
"80 |cFFFFFFFF[Runecloth]|r",
"",
"------------------------------------------------------------------------------------------------",
"Preface",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"Some |cFF1EFF00Recipes|r may require completing |cFFFFD700[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the |cFFFFFF00[Auction House]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"Leveling First Aid",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF1 - 75|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF1-40|r]",
"Craft: 50x |cFFFFFFFF[Linen Bandage]|r",
"Requires: 50 |cFFFFFFFF[Linen Cloth]|r",
"",
"[|cFF33FFFF40-75|r]",
"Craft: 45x |cFFFFFFFF[Heavy Linen Bandage]|r",
"Requires: 90 |cFFFFFFFF[Linen Cloth]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Journeyman First Aid]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Arnok]|r / |cFF33FF99[Orgrimmar, Durotar]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Pand Stonebinder]|r / |cFF33FF99[Thunder Bluff, Mulgore]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Mary Edras]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Nissa Firestone]|r / |cFF33FF99[Ironforge, Dun Morogh]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Dannelor]|r / |cFF33FF99[Darnassus, Teldrassil]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Shaina Fuller]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF75 - 150|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF75-80|r]",
"Craft: 15x |cFFFFFFFF[Heavy Linen Bandage]|r",
"Requires: 30 |cFFFFFFFF[Linen Cloth]|r",
"",
"[|cFF33FFFF80-115|r]",
"Craft: 60x |cFFFFFFFF[Wool Bandage]|r",
"Requires: 60 |cFFFFFFFF[Wool Cloth]|r",
"",
"[|cFF33FFFF115-150|r]",
"Craft: 60x |cFFFFFFFF[Heavy Wool Bandage]|r",
"Requires: 120 |cFFFFFFFF[Wool Cloth]|r",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Expert First Aid - Under Wraps]|r (Raises Cap [150] > [225])",
"      |cFF1EFF00[Manual: Heavy Silk Bandage]|r",
"      |cFF1EFF00[Manual: Mageweave Bandage]|r",
"",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Balai Lok'Wein]|r / |cFF33FF99[Brackenwall Village, Dustwallow Marsh]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Deneb Walker]|r / |cFF33FF99[Stormgarde Keep, Arathi Highlands]|r",
"--------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF150 - 225|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF150-180|r]",
"Craft: 50x |cFFFFFFFF[Silk Bandage]|r",
"Requires: 50 |cFFFFFFFF[Silk Cloth]|r",
"",
"[|cFF33FFFF180-210|r]",
"Craft: 50x |cFFFFFFFF[Heavy Silk Bandage]|r",
"Requires: 100 |cFFFFFFFF[Silk Cloth]|r",
"",
"[|cFF33FFFF210-225|r]",
"Craft: 30x |cFFFFFFFF[Mageweave Bandage]|r",
"Requires: 30 |cFFFFFFFF[Mageweave Cloth]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN: |cFF1EFF00[Artisan First Aid]|r (Requires Character Level 35; Raises Cap [225] > [300])",
"",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Arnok]|r / |cFF33FF99[Orgrimmar, Durotar]|r: |cFFFFD700[! Horde Trauma]|r ",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Nissa Firestone]|r / |cFF33FF99[Ironforge, Dun Morogh]|r: |cFFFFD700[! Alliance Trauma]|r ",
"",
"      Both quests will lead to [|cFFFFD700[! Triage]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Doctor Gregory Victor]|r / |cFF33FF99[Hammerfall, Arathi Highlands]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Doctor Gustaf VanHowzen]|r / |cFF33FF99[Theramore Isle, Dustwallow Marsh]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF225 - 300|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF225-240|r]",
"Craft: 30x |cFFFFFFFF[Mageweave Bandage]|r",
"Requires: 30 |cFFFFFFFF[Mageweave Cloth]|r",
"",
"[|cFF33FFFF240-260|r]",
"------------------------------------------------------------------------------------------------",
"LEARN:",
"      |cFF1EFF00[Heavy Mageweave Bandage]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Doctor Gregory Victor]|r / |cFF33FF99[Hammerfall, Arathi Highlands]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Doctor Gustaf VanHowzen]|r / |cFF33FF99[Theramore Isle, Dustwallow Marsh]|r",
"------------------------------------------------------------------------------------------------",
"Craft: 30x |cFFFFFFFF[Heavy Mageweave Bandage]|r",
"Requires: 60 |cFFFFFFFF[Mageweave Cloth]|r",
"",
"[|cFF33FFFF260-290|r]",
"------------------------------------------------------------------------------------------------",
"LEARN:",
"      |cFF1EFF00[Runecloth Bandage]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Doctor Gregory Victor]|r / |cFF33FF99[Hammerfall, Arathi Highlands]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Doctor Gustaf VanHowzen]|r / |cFF33FF99[Theramore Isle, Dustwallow Marsh]|r",
"------------------------------------------------------------------------------------------------",
"Craft: 50x |cFFFFFFFF[Runecloth Bandage]|r",
"Requires: 50 |cFFFFFFFF[Runecloth]|r",
"",
"[|cFF33FFFF290-300|r]",
"------------------------------------------------------------------------------------------------",
"LEARN:",
"      |cFF1EFF00[Heavy Runecloth Bandage]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Doctor Gregory Victor]|r / |cFF33FF99[Hammerfall, Arathi Highlands]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Doctor Gustaf VanHowzen]|r / |cFF33FF99[Theramore Isle, Dustwallow Marsh]|r",
"------------------------------------------------------------------------------------------------",
"Craft: 15x |cFFFFFFFF[Heavy Runecloth Bandage]|r",
"Requires: 30 |cFFFFFFFF[Runecloth]|r"
}
}