FirstAid = {
  buttonText = "First Aid",
  headerText = "THE FIRST AIDER",
  content = {
"-------------------------------",
"Material List",
"-------------------------------",
"|cFFFFFFFF[Linen Cloth]|r x170",
"|cFFFFFFFF[Wool Cloth]|r x180",
"|cFFFFFFFF[Silk Cloth]|r x150",
"|cFFFFFFFF[Mageweave Cloth]|r x120",
"|cFFFFFFFF[Runecloth]|r x220",
"",
"-------------------------------------------------------------------------------------------",
"Preface",
"-------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r : Friendly with Horde",
"|cFF66B2FF[A]|r : Friendly with Alliance",
"|cFFFFD700[N]|r : Neutral",
"",
"Some |cFF1EFF00Recipes|r may require completing |cFFFFFF00[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the [Auction House]",
"-------------------------------------------------------------------------------------------",
"",
"-------------------------------",
"Leveling First Aid",
"-------------------------------",
"-------------------------------",
"LEVELS: 1 - 75",
"-------------------------------",
"[1-40]",
"Craft: 50x |cFFFFFFFF[Linen Bandage]|r",
"Requires: 50 |cFFFFFFFF[Linen Cloth]|r",
"",
"[40-80]",
"Craft: 120x |cFFFFFFFF[Heavy Linen Bandage]|r",
"Requires: 120 |cFFFFFFFF[Linen Cloth]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"     |cFFFFFFFF[Journeyman First Aid]|r (Raise Cap 75>150; Requires character level 10)",
"WHERE:",
"     |cFF33FF99[Arnok]|r in |cFF66B2FF[Orgrimmar]|r",
"     |cFF33FF99[Pand Stonebinder]|r in |cFF66B2FF[Thunder Bluff]|r",
"     |cFF33FF99[Mary Edras]|r in |cFF66B2FF[Undercity]|r",
"",
"     |cFF33FF99[Nissa Firestone]|r in |cFF66B2FF[Ironforge]|r",
"     |cFF33FF99[Dannelor]|r in |cFF66B2FF[Darnassus]|r",
"     |cFF33FF99[Shaina Fuller]|r in |cFF66B2FF[Stormwind City]|r",
"------------------------------------------------------------------------------------------------",
"",
"-------------------------------",
"LEVELS: 80 - 150",
"-------------------------------",
"[80-115]",
"Craft: 60x |cFFFFFFFF[Wool Bandage]|r",
"Requires: 60 |cFFFFFFFF[Wool Cloth]|r",
"",
"[115-150]",
"Craft: 120x |cFFFFFFFF[Heavy Wool Bandage]|r",
"Requires: 120 |cFFFFFFFF[Wool Cloth]|r",
"",
"-------------------------------------------------------------------------------------------",
"PURCHASE:",
"     |cFF1EFF00[Expert First Aid - Under Wraps]|r (Raise Cap 150>225)",
"     |cFF1EFF00[Manual: Heavy Silk Bandage]|r",         
"     |cFF1EFF00[Manual: Mageweave Bandage]|r",
"WHERE:",
"             |cFF33FF99[Deneb Walker]|r in |cFF66B2FF[Arathi Highlands]|r",
"",
"             |cFF33FF99[Balai Lok'Wein]|r in |cFF66B2FF[Dustwallow Marsh]|r",
"             NOTE: Buy all three books from this vendor! Can also buy from Auction House if low level",
"--------------------------------------------------------------------------------------------",
"",
"-------------------------------",
"LEVELS: 150 - 225",
"-------------------------------",
"[150-180]",
"Craft: 70x |cFFFFFFFF[Silk Bandage]|r",
"Requires: 70 |cFFFFFFFF[Silk Cloth]|r",
"",
"[180-210]",
"Craft: 80x |cFFFFFFFF[Heavy Silk Bandage]|r",
"Requires: 80 |cFFFFFFFF[Silk Cloth]|r",
"",
"[210-225]",
"Craft: 30x |cFFFFFFFF[Mageweave Bandage]|r",
"Requires: 30 |cFFFFFFFF[Mageweave Cloth]|r",
"",
"------------------------------------------------------------------------------------------------",
"QUEST: |cFFFFFFFF[Artisan First Aid]|r (Raise Cap 225>300; Requires character level 35)",
"",
"      |cFF33FF99[Arnok]|r in |cFF66B2FF[Orgrimmar]|r: |cFFFFFF00[! Horde Trauma]|r ",
"",
"      |cFF33FF99[Nissa Firestone]|r in|cFF66B2FF[Ironforge]|r: |cFFFFFF00[! Alliance Trauma]|r ",
"",
"      Both quests will lead to |cFFFFFF00[! Triage]|r",
"      |cFF33FF99[Doctor Gustaf VanHowzen]|r in |cFF66B2FF[Theramore, Dustwallow Marsh]|r",
"",
"      |cFF33FF99[Doctor Gregory Victor]|r in |cFF66B2FF[Hammerfall, Arathi Highlands]|r",
"",
"|cFFFF8000[! Triage]|r:",
"TIPS:",
"      - Turn on health bars over patients' heads for easy monitoring",
"      - Use third-person camera view for better room visibility",
"      - Put triage bandages on action bar for quick access",
"      - Position yourself centrally in the room",
"      - Pre-select next patient while bandaging current one",
"      - Prioritize patients by injury severity (start from left)",
"      - Don't panic! Usually won't die before you finish the round",
"------------------------------------------------------------------------------------------------",
"",
"-------------------------------",
"LEVELS: 225 - 300",
"-------------------------------",
"[225-240]",
"Craft: 30x |cFFFFFFFF[Mageweave Bandage]|r",
"Requires: 30 |cFFFFFFFF[Mageweave Cloth]|r",
"",
"[240-260]",
"Talk to |cFF33FF99[Doctor Gustaf VanHowzen]|r / |cFF33FF99[Doctor Gregory Victor]|r to learn:",
"|cFF1EFF00[Heavy Mageweave Bandage]|r",
"",
"Craft: 60x |cFFFFFFFF[Heavy Mageweave Bandage]|r",
"Requires: 60 |cFFFFFFFF[Mageweave Cloth]|r",
"",
"[260-290]",
"Talk to |cFF33FF99[Doctor Gustaf VanHowzen]|r / |cFF33FF99[Doctor Gregory Victor]|r to learn:",
"|cFF1EFF00[Runecloth Bandage]|r",
"",
"Craft: 80x |cFFFFFFFF[Runecloth Bandage]|r",
"Requires: 80 |cFFFFFFFF[Runecloth]|r",
"",
"[290-300]",
"Talk to |cFF33FF99[Doctor Gustaf VanHowzen]|r / |cFF33FF99[Doctor Gregory Victor]|r to learn:",
"|cFF1EFF00[Heavy Runecloth Bandage]|r",
"",
"Craft: 140x |cFFFFFFFF[Heavy Runecloth Bandage]|r",
"Requires: 140 |cFFFFFFFF[Runecloth]|r"
}
}