Fishing = {
  buttonText = "Fishing",
  headerText = "THE ANGLER",
  content = {
"------------------------------------------------------------------------------------------------",
"Gear List",
"------------------------------------------------------------------------------------------------",
"|cFFFFFFFF[Fishing Pole]|r (sold by Trade Supplies and Fishing Supplies vendors)",
"|cFFFFFFFF[Shiny Bauble]|r (+25, min skill 1)",
"Lures for higher skill: see the Lures list below.",
"",
"------------------------------------------------------------------------------------------------",
"Preface",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"NOTE: Fishing levels by number of catches, not zone difficulty.",
"Fish you catch can be cooked, see the Cooking guide.",
"Wowhead marks this page Beta and says it may change before launch.",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"Leveling Fishing",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF1 - 75|r]",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"Zones: any starter zone.",
"Gear: a Fishing Pole. Use a Shiny Bauble below skill 25.",
"At skill 25 you have a 100% catch rate in starter zones.",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Apprentice Fishing]|r",
"WHERE (Alliance):",
"      |cFF66B2FF[A]|r |cFF33FF99[Lee Brown]|r / |cFF33FF99[Goldshire, Elwynn Forest]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Paxton Ganter]|r / |cFF33FF99[Brewnall Village, Dun Morogh]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Androl Oakhand]|r / |cFF33FF99[Rut'theran Village, Teldrassil]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Arnold Leland]|r / |cFF33FF99[Trade District, Stormwind City]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Astaia]|r / |cFF33FF99[Temple Gardens, Darnassus]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Grimnur Stonebrand]|r / |cFF33FF99[Forlorn Cavern, Ironforge]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Warg Deepwater]|r / |cFF33FF99[Thelsamar, Loch Modan]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Harold Riggs]|r / |cFF33FF99[Menethil Harbor, Wetlands]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Matthew Hooper]|r / |cFF33FF99[Lakeshire, Redridge Mountains]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Donald Rabonne]|r / |cFF33FF99[Southshore, Hillsbrad Foothills]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Brannock]|r / |cFF33FF99[Feathermoon Stronghold, Feralas]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Myizz Luckycatch]|r / |cFF33FF99[Booty Bay, Stranglethorn Vale]|r",
"WHERE (Horde):",
"      |cFFFF0000[H]|r |cFF33FF99[Lau'Tiki]|r / |cFF33FF99[South of Sen'jin Village, Durotar]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Uthan Stillwater]|r / |cFF33FF99[Bloodhoof Village, Mulgore]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Clyde Kellen]|r / |cFF33FF99[Brightwater Lake, Tirisfal Glades]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Lumak]|r / |cFF33FF99[Valley of Honor, Orgrimmar]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Kah Mistrunner]|r / |cFF33FF99[Middle Tier, Thunder Bluff]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Armand Cromwell]|r / |cFF33FF99[Magic Quarter, Undercity]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Kil'Hiwana]|r / |cFF33FF99[South of Blackfathom Deeps, Ashenvale]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Lui'Mala]|r / |cFF33FF99[Shadowprey Village, Desolace]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Katoom the Angler]|r / |cFF33FF99[Revantusk Village, The Hinterlands]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Myizz Luckycatch]|r / |cFF33FF99[Booty Bay, Stranglethorn Vale]|r",
"WHERE (Neutral):",
"      |cFFFFD700[N]|r |cFF33FF99[Fenn Fairweather]|r / |cFF33FF99[Shen'dar Village, Zephras Isle]|r",
"      |cFFFFD700[N]|r |cFF33FF99[Baelann Swiftcurrent]|r / |cFF33FF99[Valanaar, Zephras Isle]|r",
"      |cFFFFD700[N]|r |cFF33FF99[Krix]|r / |cFF33FF99[Powderfuse Port, Riverglades]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF75 - 150|r]",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"Zones: fish in a capital city. No lure is needed at skill 75.",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Journeyman Fishing]|r (Raises Cap [75] > [150])",
"WHERE:",
"      Any Fishing trainer, in a capital city:",
"      |cFF66B2FF[A]|r Darnassus, Ironforge, Stormwind City",
"      |cFFFF0000[H]|r Orgrimmar, Thunder Bluff, Undercity",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF150 - 225|r]",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"Zones: Dustwallow Marsh or Stranglethorn Vale.",
"Stranglethorn is generally better for Horde, Dustwallow is",
"more accessible for Alliance. Skill 225 gives a 100% catch",
"rate there, so use lures. You can also keep fishing in a",
"capital city if you do not need to make money.",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Expert Fishing - The Bass and You]|r (Raises Cap [150] > [225])",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Old Man Heming]|r / |cFF33FF99[Booty Bay, Stranglethorn Vale]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF225 - 300|r]",
"------------------------------------------------------------------------------------------------",
"|cFFFF8000UNVERIFIED: Wowhead lists 225-300 as coming soon|r",
"------------------------------------------------------------------------------------------------",
"QUEST:",
"      |cFFFFD700[! Nat Pagle, Angler Extreme]|r (Requires Character Level 35, Fishing 225)",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Nat Pagle]|r / |cFF33FF99[Dustwallow Marsh]|r",
"",
"Catch 4 unique fish. They can only be caught during the quest:",
"      |cFFFFFFFF[Feralas Ahi]|r: Feralas, southeast of Dire Maul",
"      |cFFFFFFFF[Misty Reed Mahi Mahi]|r: east coast, Swamp of Sorrows",
"      |cFFFFFFFF[Sar'theris Striker]|r: west coast, Desolace",
"      |cFFFFFFFF[Savage Coast Blue Sailfin]|r: west coast, Stranglethorn Vale",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"Zone Requirements",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"Minimum skill to fish / skill for a 100% catch rate:",
"",
"[|cFF33FFFF1 / 25|r]",
"      Dun Morogh, Durotar, Elwynn Forest, Mulgore, Teldrassil, Tirisfal Glades,",
"      Zephras Isle",
"[|cFF33FFFF1 / 75|r]",
"      The Barrens, Blackfathom Deeps, Darkshore, Darnassus, The Deadmines,",
"      Ironforge, Loch Modan, Orgrimmar, Silverpine Forest, Stormwind City,",
"      Thunder Bluff, Undercity, The Wailing Caverns, Westfall",
"[|cFF33FFFF55 / 150|r]",
"      Ashenvale, Duskwood, Hillsbrad Foothills, Redridge Mountains, Stonetalon",
"      Mountains, Wetlands",
"[|cFF33FFFF130 / 225|r]",
"      Alterac Mountains, Arathi Highlands, Desolace, Dustwallow Marsh, Scarlet",
"      Monastery, Stranglethorn Vale (not Jaguero Isle), Swamp of Sorrows,",
"      Thousand Needles",
"[|cFF33FFFF205 / 300|r]",
"      Azshara (not Bay of Storms, Hetaera's Clutch, Scalebeard's Cave), Felwood,",
"      Feralas, The Hinterlands, Maraudon, Moonglade, Stranglethorn Vale (Jaguero",
"      Isle), Tanaris, The Temple of Atal'Hakkar, Un'Goro Crater, Western",
"      Plaguelands",
"[|cFF33FFFF330 / 425|r] (above the beta cap)",
"      Azshara (Bay of Storms, Hetaera's Clutch, Scalebeard's Cave), Burning",
"      Steppes, Deadwind Pass, Eastern Plaguelands, Feralas (Jademir Lake),",
"      Scholomance, Silithus, Stratholme, Winterspring, Zul'Gurub",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"Gear and Boosts",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"|cFF33FF99Fishing Poles|r",
"      |cFFFFFFFF[Blump Family Fishing Pole]|r  +3 (min skill 1)",
"      |cFFFFFFFF[Strong Fishing Pole]|r  +5 (min skill 10)",
"      |cFFFFFFFF[Big Iron Fishing Pole]|r  +20 (min skill 100)",
"      |cFFFFFFFF[Nat Pagle's Extreme Angler FC-5000]|r  +25 (min skill 100, Horde only)",
"      |cFFFFFFFF[Arcanite Fishing Pole]|r  +35 (min skill 300)",
"",
"|cFF33FF99Lures|r (temporary)",
"      |cFFFFFFFF[Shiny Bauble]|r  +25 (min skill 1)",
"      |cFFFFFFFF[Nightcrawlers]|r  +50 (min skill 50)",
"      |cFFFFFFFF[Aquadynamic Fish Lens]|r  +50 (min skill 50)",
"      |cFFFFFFFF[Bright Baubles]|r  +75 (min skill 100)",
"      |cFFFFFFFF[Flesh Eating Worm]|r  +75 (min skill 100)",
"      |cFFFFFFFF[Aquadynamic Fish Attractor]|r  +100 (min skill 100)",
"",
"|cFF33FF99Food|r (minimum character level)",
"      |cFFFFFFFF[Loch Frenzy Delight]|r  +3 (min level 5)",
"      |cFFFFFFFF[Fillet of Frenzy]|r  +5 (min level 5)",
"      |cFFFFFFFF[Bristle Whisker Catfish]|r  +8 (min level 15)",
"      |cFFFFFFFF[Rockscale Cod]|r  +12 (min level 25)",
"      |cFFFFFFFF[Filet of Redgill]|r  +18 (min level 35)",
"      |cFFFFFFFF[Spinefin Halibut]|r  +18 (min level 45)",
"",
"|cFF33FF99Equipment|r",
"      |cFFFFFFFF[Lucky Fishing Hat]|r  +5 (min skill 1)",
"      |cFFFFFFFF[Nat Pagle's Extreme Anglin' Boots]|r  +5 (min skill 1)",
"      |cFFFFFFFF[High Test Eternium Fishing Line]|r  +5 (min skill 1)",
"      |cFFFFFFFF[Enchant Gloves - Fishing]|r  +2 (min skill 1)",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"Forever Additions",
"------------------------------------------------------------------------------------------------",
"|cFF1EFF00VERIFIED: Wowhead Forever guide|r",
"Fishing can make camping items for Campfires:",
"      |cFFFFFFFF[Fish Bowl]|r: skill 20, from the trainer",
"      |cFFFFFFFF[Fishing Rack]|r: skill 140, drops from Gelihast in",
"      Blackfathom Deeps",
"      |cFFFFFFFF[Fishing Hut]|r: skill 300, from the Blueprint: Fishing Hut",
"",
"Master Angler (Stranglethorn Vale): the first 50 players to",
"finish win, and the quest always rewards an Arcanite Fishing",
"Pole and an Extravagant Extravaganza Coin.",
"Shamans can use Far Sight and Water Walking to reach schools."
  }
}
