Leatherworking = {
buttonText = "Leatherworking",
headerText = "THE LEATHERWORKER",
content = {
"-------------------------------",
"Material List",
"-------------------------------",
"|cFFFFFFFF[Ruined Leather Scraps]|r x57",
"|cFFFFFFFF[Light Leather]|r x470",
"|cFF9D9D9D[Coarse Thread]|r x310",
"|cFFFFFFFF[Medium Leather]|r x335",
"|cFF9D9D9D[Fine Thread]|r x135",
"|cFF9D9D9D[Gray Dye]|r x55",
"|cFFFFFFFF[Medium Hide]|r x20",
"|cFF9D9D9D[Salt]|r x20",
"|cFFFFFFFF[Heavy Leather]|r x195",
"|cFFFFFFFF[Heavy Hide]|r x20",
"|cFFFFFFFF[Thick Leather]|r x650",
"|cFF9D9D9D[Silken Thread]|r x225",
"|cFF9D9D9D[Heavy Silken Thread]|r x26",
"|cFFFFFFFF[Rugged Leather]|r x400",
"|cFF9D9D9D[Black Dye]|r x61",
"|cFF9D9D9D[Rune Thread]|r x71",
"|cFFFFFFFF[Runecloth]|r x100",
"",
"-------------------------------",
"LEVELING LEATHERWORKING",
"-------------------------------",
"-------------------------------",
"LEVELS: 1 - 55",
"-------------------------------",
"",
"[1-20]",
"Craft: 19x |cFFFFFFFF[Light Leather]|r",
"Requires: 57 |cFFFFFFFF[Ruined Leather Scraps]|r",
"",
"[20-45]",
"Craft: 40x |cFFFFFFFF[Light Armor Kit]|r",
"Requires: 40 |cFFFFFFFF[Light Leather]|r",
"",
"Alternative if no Ruined Leather Scraps:",
"[1-45]",
"Craft: 40x |cFFFFFFFF[Light Armor Kit]|r",
"Requires: 40 |cFFFFFFFF[Light Leather]|r",
"",
"[45-55]",
"Craft: 20x |cFFFFFFFF[Handstitched Leather Cloak]|r",
"Requires: 40 |cFFFFFFFF[Light Leather]|r, 20 |cFF9D9D9D[Coarse Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"            |cFFFFFFFF[Journeyman Leatherworker]|r (Raise Cap 75>150; Requires character level 10)",
"WHERE:",
"      HORDE:",
"            |cFF33FF99[Arthur Moore]|r found in |cFF66B2FF[Undercity]|r",
"            |cFF33FF99[Karolek]|r found in |cFF66B2FF[Orgrimmar]|r",
"            |cFF33FF99[Tarn]|r found in |cFF66B2FF[Thunder Bluff]|r",
"      ALLIANCE:",
"            |cFF33FF99[Simon Tanner]|r found in |cFF66B2FF[Stormwind City]|r",
"            |cFF33FF99[Faldron]|r found in |cFF66B2FF[Darnassus]|r",
"            |cFF33FF99[Fimble Finespindle]|r found in |cFF66B2FF[Ironforge]|r",
"------------------------------------------------------------------------------------------------",
"",
"-------------------------------",
"LEVELS: 55 - 137",
"-------------------------------",
"",
"[55-100]",
"Craft: 50x |cFFFFFFFF[Embossed Leather Gloves]|r",
"Requires: 150 |cFFFFFFFF[Light Leather]|r, 100 |cFF9D9D9D[Coarse Thread]|r",
"",
"[100-125]",
"Craft: 40x |cFFFFFFFF[Fine Leather Belt]|r",
"Requires: 240 |cFFFFFFFF[Light Leather]|r, 80 |cFF9D9D9D[Coarse Thread]|r",
"NOTE: Keep Fine Leather Belts. Make Cured Medium Hide if you have cheap Medium Hide",
"",
"Optional:",
"Craft: |cFFFFFFFF[Cured Medium Hide]|r",
"Requires: 1 |cFFFFFFFF[Medium Hide]|r, 1 |cFF9D9D9D[Salt]|r (per hide)",
"NOTE: Make as many as you can if Medium Hide is cheap. Keep for making Dark Leather Belt",
"",
"[125-137]",
"Craft: 15x |cFFFFFFFF[Dark Leather Boots]|r",
"Requires: 60 |cFFFFFFFF[Medium Leather]|r, 30 |cFF9D9D9D[Fine Thread]|r, 15 |cFF9D9D9D[Gray Dye]|r",
"",
"Alternative if you made Cured Medium Hide:",
"Craft: |cFFFFFFFF[Dark Leather Belt]|r",
"Requires: 4 |cFFFFFFFF[Medium Leather]|r, 1 |cFFFFFFFF[Fine Leather Belt]|r, 1 |cFFFFFFFF[Cured Medium Hide]|r",
"1 |cFF9D9D9D[Fine Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"            |cFFFFFFFF[Expert Leatherworker]|r (Raise Cap 150>225; Requires character level 20)",
"WHERE:",
"      ALLIANCE:",
"            |cFF33FF99[Telonis]|r found in |cFF66B2FF[Darnassus]|r",
"      HORDE:",
"            |cFF33FF99[Una]|r found in |cFF66B2FF[Thunder Bluff]|r",
"------------------------------------------------------------------------------------------------",
"",
"-------------------------------",
"LEVELS: 137 - 205",
"-------------------------------",
"",
"[137-150]",
"Craft: 20x |cFFFFFFFF[Dark Leather Pants]|r",
"Requires: 240 |cFFFFFFFF[Medium Leather]|r, 20 |cFF9D9D9D[Gray Dye]|r, 20 |cFF9D9D9D[Fine Thread]|r",
"",
"[150-155]",
"Craft: 7x |cFFFFFFFF[Heavy Leather]|r",
"Requires: 35 |cFFFFFFFF[Medium Leather]|r",
"",
"Alternative recipe:",
"",
"-------------------------------------------------------------------------------------------",
"PURCHASE:",
"            |cFF1EFF00[Pattern: Heavy Leather Ball]|r",
"WHERE:",
"      ALLIANCE:",
"            |cFF33FF99[Bombus Finespindle]|r found in |cFF66B2FF[Ironforge]|r",
"      HORDE:",
"            |cFF33FF99[Tamar]|r found in |cFF66B2FF[Orgrimmar]|r",
"--------------------------------------------------------------------------------------------",
"",
"Craft: 7x |cFFFFFFFF[Heavy Leather Ball]|r",
"Requires: 14 |cFFFFFFFF[Heavy Leather]|r, 7 |cFF9D9D9D[Fine Thread]|r",
"",
"[155-165]",
"Craft: 20x |cFFFFFFFF[Cured Heavy Hide]|r",
"Requires: 20 |cFFFFFFFF[Heavy Hide]|r, 60 |cFF9D9D9D[Salt]|r",
"NOTE: Save these for later recipes.",
"",
"Alternative without Heavy Hide:",
"",
"[155-180]",
"Craft: 15x |cFFFFFFFF[Heavy Armor Kit]|r",
"Requires: 75 |cFFFFFFFF[Heavy Leather]|r, 15 |cFF9D9D9D[Fine Thread]|r",
"",
"-------------------------------------------------------------------------------------------",
"PURCHASE:",
"            |cFF1EFF00[Pattern: Barbaric Leggings]|r",
"WHERE:",
"            [Auction House] or [World Drop] from level [39-48] mobs",
"--------------------------------------------------------------------------------------------",
"",
"[180-200]",
"Craft: 23x |cFFFFFFFF[Barbaric Leggings]|r",
"Requires: 230 |cFFFFFFFF[Heavy Leather]|r, 23 |cFF00FF00[Moss Agate]|r",
"",
"With Heavy Hide:",
"",
"[165-180]",
"Craft: 15x |cFFFFFFFF[Heavy Armor Kit]|r",
"Requires: 75 |cFFFFFFFF[Heavy Leather]|r, 15 |cFF9D9D9D[Fine Thread]|r",
"",
"[180-190]",
"Craft: 10x |cFFFFFFFF[Barbaric Shoulders]|r",
"Requires: 80 |cFFFFFFFF[Heavy Leather]|r, 10 |cFFFFFFFF[Cured Heavy Hide]|r, 20 |cFF9D9D9D[Fine Thread]|r",
"",
"[190-200]",
"Craft: 10x |cFFFFFFFF[Guardian Gloves]|r",
"Requires: 40 |cFFFFFFFF[Heavy Leather]|r, 10 |cFFFFFFFF[Cured Heavy Hide]|r, 10 |cFF9D9D9D[Silken Thread]|r",
"",
"[200-205]",
"Craft: 5x |cFFFFFFFF[Thick Armor Kit]|r",
"Requires: 25 |cFFFFFFFF[Thick Leather]|r, 5 |cFF9D9D9D[Silken Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"            |cFFFFFFFF[Artisan Leatherworker]|r (Raise Cap 225>300; Requires character level 35)",
"WHERE:",
"      ALLIANCE:",
"            |cFF33FF99[Drakk Stonehand]|r found in |cFF66B2FF[Hinterlands, Aerie Peak]|r",
"            (Inside Wildhammer Keep, left side down one layer of stairs)",
"      HORDE:",
"            |cFF33FF99[Hahrana Ironhide]|r found in |cFF66B2FF[Feralas, Camp Mojache]|r",
"------------------------------------------------------------------------------------------------",
"",
"-------------------------------",
"SPECIALIZATION INFO",
"-------------------------------",
"",
"At Leatherworking 225 and character level 40, choose one specialization:",
"|cFF1EFF00[Dragonscale Leatherworking]|r - Mail-type gear",
"|cFF1EFF00[Elemental Leatherworking]|r - Elemental resistance & Leather agility gear",
"|cFF1EFF00[Tribal Leatherworking]|r - Leather intellect/agility gear & Devilsaur Armor set",
"NOTE: Specializations are optional but recommended at level 40",
"",
"-------------------------------",
"LEVELS: 205 - 260",
"-------------------------------",
"",
"[205-235]",
"Craft: 40x |cFFFFFFFF[Nightscape Headband]|r",
"Requires: 200 |cFFFFFFFF[Thick Leather]|r, 80 |cFF9D9D9D[Silken Thread]|r",
"NOTE: These sell well to vendors, more profitable than Thick Armor Kits",
"",
"[235-250]",
"Craft: 15x |cFFFFFFFF[Nightscape Pants]|r",
"Requires: 210 |cFFFFFFFF[Thick Leather]|r, 60 |cFF9D9D9D[Silken Thread]|r",
"",
"[250-260]",
"Craft: 13x |cFFFFFFFF[Nightscape Boots]|r",
"Requires: 208 |cFFFFFFFF[Thick Leather]|r, 26 |cFF9D9D9D[Heavy Silken Thread]|r",
"",
"-------------------------------",
"LEVELS: 260 - 290",
"-------------------------------",
"",
"-------------------------------------------------------------------------------------------",
"PURCHASE:",
"            |cFF1EFF00[Pattern: Wicked Leather Gauntlets]|r (Limited Supply)",
"WHERE:",
"      ALLIANCE:",
"            |cFF33FF99[Leonard Porter]|r found in |cFF66B2FF[Western Plaguelands]|r",
"      HORDE:",
"            |cFF33FF99[Werg Thickblade]|r found in |cFF66B2FF[Tirisfal Glades]|r",
"            NOTE: Limited supply with long respawn timer. Buy from Auction House if sold out",
"--------------------------------------------------------------------------------------------",
"",
"Craft: 33x |cFFFFFFFF[Wicked Leather Gauntlets]|r",
"Requires: 264 |cFFFFFFFF[Rugged Leather]|r, 33 |cFF9D9D9D[Black Dye]|r, 33 |cFF9D9D9D[Rune Thread]|r",
"",
"Alternative recipe:",
"NOTE: Recipe requires Leatherworking 265, make 6-7 more Nightscape Boots to reach 265",
"",
"-------------------------------------------------------------------------------------------",
"FARM:",
"            |cFF1EFF00[Pattern: Wicked Leather Bracers]|r",
"WHERE:",
"            [Auction House] or [World Drop] from |cFF33FF99[Legashi Rogue]|r found in |cFF66B2FF[Azshara]|r (5% drop rate)",
"--------------------------------------------------------------------------------------------",
"",
"Craft: 28x |cFFFFFFFF[Wicked Leather Bracers]|r",
"Requires: 224 |cFFFFFFFF[Rugged Leather]|r, 28 |cFF9D9D9D[Black Dye]|r, 28 |cFF9D9D9D[Rune Thread]|r",
"",
"-------------------------------",
"LEVELS: 290 - 300",
"-------------------------------",
"",
"-------------------------------------------------------------------------------------------",
"PURCHASE:",
"            |cFF1EFF00[Pattern: Runic Leather Headband]|r (Limited Supply)",
"WHERE:",
"            |cFF33FF99[Jase Farlane]|r found in |cFF66B2FF[Eastern Plaguelands]|r",
"            NOTE: Limited supply with very long respawn timer. Check Auction House if sold out",
"--------------------------------------------------------------------------------------------",
"",
"Craft: 10x |cFFFFFFFF[Runic Leather Headband]|r",
"Requires: 140 |cFFFFFFFF[Rugged Leather]|r, 100 |cFFFFFFFF[Runecloth]|r, 10 |cFF9D9D9D[Rune Thread]|r",
"",
"Alternative recipes:",
"",
"-------------------------------------------------------------------------------------------",
"FARM:",
"            |cFF1EFF00[Pattern: Wicked Leather Headband]|r",
"WHERE:",
"            [World Drop] from |cFF33FF99[Jadefire Trickster]|r found in |cFF66B2FF[Felwood]|r (2% drop rate)",
"            NOTE: Worth buying if cheaper than 100 Runecloth at Auction House",
"--------------------------------------------------------------------------------------------",
"",
"Craft: 10x |cFFFFFFFF[Wicked Leather Headband]|r",
"Requires: 120 |cFFFFFFFF[Rugged Leather]|r, 10 |cFF9D9D9D[Black Dye]|r, 10 |cFF9D9D9D[Rune Thread]|r",
"",
"-------------------------------------------------------------------------------------------",
"FARM:",
"            |cFF1EFF00[Pattern: Runic Leather Belt]|r (World Drop)",
"            |cFF1EFF00[Pattern: Runic Leather Bracers]|r (World Drop)",
"            |cFF1EFF00[Pattern: Runic Leather Gauntlets]|r (World Drop)",
"PURCHASE:",
"            [Auction House]",
"--------------------------------------------------------------------------------------------",
"",
"Craft: 10x |cFFFFFFFF[Runic Leather Belt]|r",
"Requires: 120 |cFFFFFFFF[Rugged Leather]|r, 100 |cFFFFFFFF[Runecloth]|r, 10 |cFF9D9D9D[Rune Thread]|r",
"",
"Craft: 12x |cFFFFFFFF[Runic Leather Bracers]|r",
"Requires: 72 |cFFFFFFFF[Rugged Leather]|r, 12 |cFF00FF00[Black Pearl]|r, 72 |cFFFFFFFF[Runecloth]|r",
"12 |cFF9D9D9D[Rune Thread]|r",
"",
"Craft: 14x |cFFFFFFFF[Runic Leather Gauntlets]|r",
"Requires: 140 |cFFFFFFFF[Rugged Leather]|r, 84 |cFFFFFFFF[Runecloth]|r, 14 |cFF9D9D9D[Rune Thread]|r"
}
}