Leatherworking = {
buttonText = "Leatherworking",
headerText = "THE LEATHERWORKER",
content = {
"------------------------------------------------------------------------------------------------",
"Material List",
"------------------------------------------------------------------------------------------------",
"57 |cFFFFFFFF[Ruined Leather Scraps]|r",
"470 |cFFFFFFFF[Light Leather]|r",
"310 |cFF9D9D9D[Coarse Thread]|r",
"335 |cFFFFFFFF[Medium Leather]|r",
"135 |cFF9D9D9D[Fine Thread]|r",
"55 |cFF9D9D9D[Gray Dye]|r",
"20 |cFFFFFFFF[Medium Hide]|r",
"20 |cFF9D9D9D[Salt]|r",
"195 |cFFFFFFFF[Heavy Leather]|r",
"20 |cFFFFFFFF[Heavy Hide]|r",
"650 |cFFFFFFFF[Thick Leather]|r",
"225 |cFF9D9D9D[Silken Thread]|r",
"26 |cFF9D9D9D[Heavy Silken Thread]|r",
"400 |cFFFFFFFF[Rugged Leather]|r",
"61 |cFF9D9D9D[Black Dye]|r",
"71 |cFF9D9D9D[Rune Thread]|r",
"100 |cFFFFFFFF[Runecloth]|r",
"",
"------------------------------------------------------------------------------------------------",
"Preface",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"Some |cFF1EFF00Recipes|r may require completing |cFFFFD700[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the |cFFFFFF00[Auction House]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"LEVELING LEATHERWORKING",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF1 - 55|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF1-20|r]",
"Craft: 19x |cFFFFFFFF[Light Leather]|r",
"Requires: 57 |cFFFFFFFF[Ruined Leather Scraps]|r",
"",
"[|cFF33FFFF20-45|r]",
"Craft: 40x |cFFFFFFFF[Light Armor Kit]|r",
"Requires: 40 |cFFFFFFFF[Light Leather]|r",
"",
"Alternative if no Ruined Leather Scraps:",
"[|cFF33FFFF1-45|r]",
"Craft: 40x |cFFFFFFFF[Light Armor Kit]|r",
"Requires: 40 |cFFFFFFFF[Light Leather]|r",
"",
"[|cFF33FFFF45-55|r]",
"Craft: 20x |cFFFFFFFF[Handstitched Leather Cloak]|r",
"Requires: 40 |cFFFFFFFF[Light Leather]|r, 20 |cFF9D9D9D[Coarse Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Journeyman Leatherworker]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Arthur Moore]|r  /  |cFF33FF99[Undercity, Tirisfal Glades]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Karolek]|r  /  |cFF33FF99[Orgrimmar, Durotar]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Tarn]|r  /  |cFF33FF99[Thunder Bluff, Mulgore]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Simon Tanner]|r  /  |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Faldron]|r  /  |cFF33FF99[Darnassus, Teldrassil]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Fimble Finespindle]|r  /  |cFF33FF99[Ironforge, Dun Morogh]|r",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF55 - 137|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF55-100|r]",
"Craft: 50x |cFFFFFFFF[Embossed Leather Gloves]|r",
"Requires: 150 |cFFFFFFFF[Light Leather]|r, 100 |cFF9D9D9D[Coarse Thread]|r",
"",
"[|cFF33FFFF100-125|r]",
"Craft: 40x |cFFFFFFFF[Fine Leather Belt]|r",
"Requires: 240 |cFFFFFFFF[Light Leather]|r, 80 |cFF9D9D9D[Coarse Thread]|r",
"NOTE: Keep Fine Leather Belts. Make Cured Medium Hide if you have cheap Medium Hide",
"",
"      |cFFB2FF66Alternative Recipes|r:",
"      Craft: |cFFFFFFFF[Cured Medium Hide]|r",
"      Requires: 1 |cFFFFFFFF[Medium Hide]|r, 1 |cFF9D9D9D[Salt]|r (per hide)",
"      NOTE: Make as many as you can if Medium Hide is cheap. Keep for making Dark Leather Belt",
"",
"[|cFF33FFFF125-137|r]",
"Craft: 15x |cFFFFFFFF[Dark Leather Boots]|r",
"Requires: 60 |cFFFFFFFF[Medium Leather]|r, 30 |cFF9D9D9D[Fine Thread]|r, 15 |cFF9D9D9D[Gray Dye]|r",
"",
"      |cFFB2FF66Alternative Recipes|r if |cFFFFFFFF[Cured Medium Hide]|r used:",
"      Craft: |cFFFFFFFF[Dark Leather Belt]|r",
"      Requires: 4 |cFFFFFFFF[Medium Leather]|r, 1 |cFFFFFFFF[Fine Leather Belt]|r, 1 |cFFFFFFFF[Cured Medium Hide]|r, 1 |cFF9D9D9D[Fine Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Expert Leatherworker]|r (Requires Character Level 20; Raises Cap [150] > [225])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Una]|r  /  |cFF33FF99[Thunder Bluff, Mulgore]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Telonis]|r  /  |cFF33FF99[Darnassus, Teldrassil]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF137 - 205|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF137-150|r]",
"Craft: 20x |cFFFFFFFF[Dark Leather Pants]|r",
"Requires: 240 |cFFFFFFFF[Medium Leather]|r, 20 |cFF9D9D9D[Gray Dye]|r, 20 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF150-155|r]",
"Craft: 7x |cFFFFFFFF[Heavy Leather]|r",
"Requires: 35 |cFFFFFFFF[Medium Leather]|r",
"",
"     |cFFB2FF66Alternative Recipes|r:",
"     Craft: 7x |cFFFFFFFF[Heavy Leather Ball]|r",
"     Requires: 14 |cFFFFFFFF[Heavy Leather]|r, 7 |cFF9D9D9D[Fine Thread]|r",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Pattern: Heavy Leather Ball]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Tamar]|r  /  |cFF33FF99[Orgrimmar, Durotar]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Bombus Finespindle]|r  /  |cFF33FF99[Ironforge, Dun Morogh]|r",
"--------------------------------------------------------------------------------------------",
"",
"[|cFF33FFFF155-165|r]",
"Craft: 20x |cFFFFFFFF[Cured Heavy Hide]|r",
"Requires: 20 |cFFFFFFFF[Heavy Hide]|r, 60 |cFF9D9D9D[Salt]|r",
"NOTE: Save these for later recipes.",
"",
"     |cFFB2FF66Alternative Recipes|r:",
"     [|cFF33FFFF155-180|r]",
"     Craft: 15x |cFFFFFFFF[Heavy Armor Kit]|r",
"     Requires: 75 |cFFFFFFFF[Heavy Leather]|r, 15 |cFF9D9D9D[Fine Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Pattern: Barbaric Leggings]|r",
"WHERE:",
"      |cFFFFFF00[Auction House]|r",
"      |cFF0070DD[World Drop]|r",
"--------------------------------------------------------------------------------------------",
"[|cFF33FFFF180-200|r]",
"Craft: 23x |cFFFFFFFF[Barbaric Leggings]|r",
"Requires: 230 |cFFFFFFFF[Heavy Leather]|r, 23 |cFF00FF00[Moss Agate]|r",
"",
"With Heavy Hide:",
"",
"[|cFF33FFFF165-180|r]",
"Craft: 15x |cFFFFFFFF[Heavy Armor Kit]|r",
"Requires: 75 |cFFFFFFFF[Heavy Leather]|r, 15 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF180-190|r]",
"Craft: 10x |cFFFFFFFF[Barbaric Shoulders]|r",
"Requires: 80 |cFFFFFFFF[Heavy Leather]|r, 10 |cFFFFFFFF[Cured Heavy Hide]|r, 20 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF190-200|r]",
"Craft: 10x |cFFFFFFFF[Guardian Gloves]|r",
"Requires: 40 |cFFFFFFFF[Heavy Leather]|r, 10 |cFFFFFFFF[Cured Heavy Hide]|r, 10 |cFF9D9D9D[Silken Thread]|r",
"",
"[|cFF33FFFF200-205|r]",
"Craft: 5x |cFFFFFFFF[Thick Armor Kit]|r",
"Requires: 25 |cFFFFFFFF[Thick Leather]|r, 5 |cFF9D9D9D[Silken Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Artisan Leatherworker]|r (Requires Character Level 35; Raises Cap [225] > [300])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Hahrana Ironhide]|r  /  |cFF33FF99[Feralas, Camp Mojache]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Drakk Stonehand]|r  /  |cFF33FF99[Hinterlands, Aerie Peak]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF205 - 260|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF205-235|r]",
"Craft: 40x |cFFFFFFFF[Nightscape Headband]|r",
"Requires: 200 |cFFFFFFFF[Thick Leather]|r, 80 |cFF9D9D9D[Silken Thread]|r",
"NOTE: These sell well to vendors, more profitable than Thick Armor Kits",
"",
"[|cFF33FFFF235-250|r]",
"Craft: 15x |cFFFFFFFF[Nightscape Pants]|r",
"Requires: 210 |cFFFFFFFF[Thick Leather]|r, 60 |cFF9D9D9D[Silken Thread]|r",
"",
"[|cFF33FFFF250-260|r]",
"Craft: 13x |cFFFFFFFF[Nightscape Boots]|r",
"Requires: 208 |cFFFFFFFF[Thick Leather]|r, 26 |cFF9D9D9D[Heavy Silken Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF260 - 290|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Pattern: Wicked Leather Gauntlets]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Werg Thickblade]|r  /  |cFF33FF99[Bulwark, Tirisfal Glades]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Leonard Porter]|r  /  |cFF33FF99[Chillwind Camp, Western Plaguelands]|r",
"--------------------------------------------------------------------------------------------",
"Craft: 33x |cFFFFFFFF[Wicked Leather Gauntlets]|r",
"Requires: 264 |cFFFFFFFF[Rugged Leather]|r, 33 |cFF9D9D9D[Black Dye]|r, 33 |cFF9D9D9D[Rune Thread]|r",
"",
"Alternative recipe:",
"NOTE: Recipe requires Leatherworking 265, make 6-7 more Nightscape Boots to reach 265",
"",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Pattern: Wicked Leather Bracers]|r",
"WHERE:",
"      |cFFFFFF00[Auction House]|r",
"      |cFF33FF99[Legashi Rogue]|r / |cFF33FF99[Azshara]|r: |cFF0070DD[World Drop 5%]|r",
"--------------------------------------------------------------------------------------------",
"Craft: 28x |cFFFFFFFF[Wicked Leather Bracers]|r",
"Requires: 224 |cFFFFFFFF[Rugged Leather]|r, 28 |cFF9D9D9D[Black Dye]|r, 28 |cFF9D9D9D[Rune Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF290 - 300|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Pattern: Runic Leather Headband]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFF33FF99[Jase Farlane]|r  /  |cFF33FF99[Light Hope's Chapel, Eastern Plaguelands]|r",
"--------------------------------------------------------------------------------------------",
"Craft: 10x |cFFFFFFFF[Runic Leather Headband]|r",
"Requires: 140 |cFFFFFFFF[Rugged Leather]|r, 100 |cFFFFFFFF[Runecloth]|r, 10 |cFF9D9D9D[Rune Thread]|r",
"",
"      |cFFB2FF66Alternative Recipes|r",
"------------------------------------------------------------------------------------------------",
"      ACQUIRE:",
"      |cFF1EFF00[Pattern: Wicked Leather Headband]|r",
"      WHERE:",
"      |cFFFFFF00[Auction House]|r / |cFF0070DD[World Drop 2%]|r",
"--------------------------------------------------------------------------------------------",
"      Craft: 10x |cFFFFFFFF[Wicked Leather Headband]|r",
"      Requires: 120 |cFFFFFFFF[Rugged Leather]|r, 10 |cFF9D9D9D[Black Dye]|r, 10 |cFF9D9D9D[Rune Thread]|r",
"------------------------------------------------------------------------------------------------",
"      ACQUIRE:",
"      |cFF1EFF00[Pattern: Runic Leather Belt]|r",
"      |cFF1EFF00[Pattern: Runic Leather Bracers]|r",
"      |cFF1EFF00[Pattern: Runic Leather Gauntlets]|r",
"",
"      WHERE:",
"      |cFFFFFF00[Auction House]|r / |cFF0070DD[World Drop <1%]|rs",
"--------------------------------------------------------------------------------------------",
"      Craft: 10x |cFFFFFFFF[Runic Leather Belt]|r",
"      Requires: 120 |cFFFFFFFF[Rugged Leather]|r, 100 |cFFFFFFFF[Runecloth]|r, 10 |cFF9D9D9D[Rune Thread]|r",
"",
"      Craft: 12x |cFFFFFFFF[Runic Leather Bracers]|r",
"      Requires: 72 |cFFFFFFFF[Rugged Leather]|r, 12 |cFF00FF00[Black Pearl]|r, 72 |cFFFFFFFF[Runecloth]|r, 12 |cFF9D9D9D[Rune Thread]|r",
"",
"      Craft: 14x |cFFFFFFFF[Runic Leather Gauntlets]|r",
"      Requires: 140 |cFFFFFFFF[Rugged Leather]|r, 84 |cFFFFFFFF[Runecloth]|r, 14 |cFF9D9D9D[Rune Thread]|r"
}
}