Tailoring = {
buttonText = "Tailoring",
headerText = "THE TAILOR",
content = {
"------------------------------------------------------------------------------------------------",
"Material List",
"------------------------------------------------------------------------------------------------",
"204 |cFFFFFFFF[Linen Cloth]|r",
"55 |cFF9D9D9D[Coarse Thread]|r",
"135 |cFFFFFFFF[Wool Cloth]|r",
"43 |cFF9D9D9D[Fine Thread]|r",
"804 |cFFFFFFFF[Silk Cloth]|r",
"36 |cFF9D9D9D[Blue Dye]|r",
"10 |cFF9D9D9D[Bleach]|r",
"60 |cFF9D9D9D[Red Dye]|r",
"20 |cFF9D9D9D[Silken Thread]|r",
"470 |cFFFFFFFF[Mageweave Cloth]|r",
"5 |cFF9D9D9D[Orange Dye]|r",
"71 |cFF9D9D9D[Heavy Silken Thread]|r",
"1195 |cFFFFFFFF[Runecloth]|r",
"110 |cFFFFFFFF[Rugged Leather]|r",
"61 |cFF9D9D9D[Rune Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"PREFACE",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"Some |cFF1EFF00Patterns|r may require completing |cFFFFD700[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the |cFFFFFF00[Auction House]|r",
"",
"If an |cFFB2FF66Alternative Recipes|r is more expensive to craft, you can recoup gold in the |cFFFFFF00[Auction House]|r",
"",
"------------------------------------------------------------------------------------------------",
"LEVELING TAILORING",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF1 - 75|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"Farming Linen Cloth",
"------------------------------------------------------------------------------------------------",
"Mob Level Ranges to Farm |cFFFFFFFF[Linen Cloth]|r:",
"      |cFFFFFF00Start Level|r: [|cFF33FFFF5|r]",
"      |cFF1EFF00Sweet Spot|r: [|cFF33FFFF11-16|r]",
"      |cFFFF8000Overlap|r: [|cFF33FFFF16-20|r] (|cFFFFFFFF[Wool Cloth]|r)",
"      |cFFFF0000End Level|r: [|cFF33FFFF20|r]",
"",
"Best Places to Farm |cFFFFFFFF[Linen Cloth]|r:",
"      1.|cFF66B2FF[A]|r |cFF33FF99Westfall|r [|cFF33FFFF10-20|r]",
"      2.|cFF66B2FF[A]|r |cFF33FF99Loch Modan|r [|cFF33FFFF10-20|r]",
"      3.|cFFFF0000[H]|r |cFF33FF99The Barrens|r [|cFF33FFFF10-20|r]",
"      4.|cFF66B2FF[A]|r |cFF33FF99Darkshore|r [|cFF33FFFF10-20|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF1-45|r]",
"Craft: 102x |cFFFFFFFF[Bolt of Linen Cloth]|r",
"Requires: 204 |cFFFFFFFF[Linen Cloth]|r",
"NOTE: Stop at 45 if you reach it early",
"",
"[|cFF33FFFF45  -70|r]",
"Craft: 40x |cFFFFFFFF[Linen Belt]|r",
"Requires: 40 |cFFFFFFFF[Bolt of Linen Cloth]|r, 40 |cFF9D9D9D[Coarse Thread]|r",
"",
"[|cFF33FFFF70-75|r]",
"Craft: 5x |cFFFFFFFF[Reinforced Linen Cape]|r",
"Requires: 10 |cFFFFFFFF[Bolt of Linen Cloth]|r, 15 |cFF9D9D9D[Coarse Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Journeyman Tailor]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Magar]|r / |cFF33FF99[Orgrimmar, Durator]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Rhiannon Davis]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"      |cFFFF0000[H]|r |cFF33FF99[Tepa]|r / |cFF33FF99[Thunder Bluff, Mulgore]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Jormund Stonebrow]|r / |cFF33FF99[Ironforge, Dun Morogh]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Sellandus]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"      |cFF66B2FF[A]|r |cFF33FF99[Me'lynn]|r / |cFF33FF99[Darnassus, Teldrassil]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF75 - 125|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"Farming Wool Cloth",
"------------------------------------------------------------------------------------------------",
"Mob Level Ranges to Farm |cFFFFFFFF[Wool Cloth]|r:",
"      |cFFFFFF00Start Level|r: [|cFF33FFFF16|r]",
"      |cFF1EFF00Sweet Spot|r: [|cFF33FFFF16-26|r]",
"      |cFFFF8000Overlap|r: |cFFFFFFFF[Linen Cloth]|r: [|cFF33FFFF14-15|r] | |cFFFFFFFF[Silk Cloth]|r: [|cFF33FFFF28-30|r]",
"      |cFFFF0000End Level|r: [|cFF33FFFF30|r]",
"",
"Best Places to Farm |cFFFFFFFF[Wool Cloth]|r:",
"      1.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Stonetalon Mountains [|cFF33FFFF15-27|r]",
"      2.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Ashenvale [|cFF33FFFF18-30|r]",
"      3.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Redridge Mountains|r [|cFF33FFFF15-25|r]",
"      4.|cFFFF0000[H]|r |cFF33FF99Hillsbrad Foothills|r [|cFF33FFFF20-30|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF75-100|r]",
"Craft: 45x |cFFFFFFFF[Bolt of Woolen Cloth]|r",
"Requires: 135 |cFFFFFFFF[Wool Cloth]|r",
"",
"[|cFF33FFFF100-110|r]",
"Craft: 13x |cFFFFFFFF[Simple Kilt]|r",
"Requires: 52 |cFFFFFFFF[Bolt of Linen Cloth]|r, 13 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF110-125|r]",
"Craft: 15x |cFFFFFFFF[Double-stitched Woolen Shoulders]|r",
"Requires: 45 |cFFFFFFFF[Bolt of Woolen Cloth]|r, 30 |cFF9D9D9D[Fine Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:",
"      |cFF1EFF00[Expert Tailor]|r (Requires Character Level 20; Raises Cap [150] > [225])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Josef Gregorian]|r / |cFF33FF99[Undercity, Tirisfal Glades]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Georgio Bolero]|r / |cFF33FF99[Stormwind City, Elwynn Forest]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF125 - 220|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"Farming Silk Cloth",
"------------------------------------------------------------------------------------------------",
"Mob Level Ranges to Farm |cFFFFFFFF[Silk Cloth]|r:",
"      |cFFFFFF00Start Level|r: [|cFF33FFFF28|r]",
"      |cFF1EFF00Sweet Spot|r: [|cFF33FFFF30-40|r] (rate), [|cFF33FFFF36-40|r] (yield)",
"      |cFFFF8000Overlap|r: |cFFFFFFFF[Wool Cloth]|r: [|cFF33FFFF28-30|r] | |cFFFFFFFF[Runecloth]|r: [|cFF33FFFF38-40|r]",
"      |cFFFF0000End Level|r: [|cFF33FFFF40|r]",
"",
"Best Places to Farm |cFFFFFFFF[Silk Cloth]|r:",
"      1.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Alterac Mountains [|cFF33FFFF24-35|r]",
"      2.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Thousand Needles [|cFF33FFFF27-39|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF125-145|r]",
"Craft: 201x |cFFFFFFFF[Bolt of Silk Cloth]|r",
"Requires: 804 |cFFFFFFFF[Silk Cloth]|r",
"",
"[|cFF33FFFF145-160|r]",
"Craft: 18x |cFFFFFFFF[Azure Silk Hood]|r",
"Requires: 36 |cFFFFFFFF[Bolt of Silk Cloth]|r, 36 |cFF9D9D9D[Blue Dye]|r, 18 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF160-170|r]",
"Craft: 10x |cFFFFFFFF[Silk Headband]|r",
"Requires: 30 |cFFFFFFFF[Bolt of Silk Cloth]|r, 20 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF170-175|r]",
"Craft: 5x |cFFFFFFFF[Formal White Shirt]|r",
"Requires: 15 |cFFFFFFFF[Bolt of Silk Cloth]|r, 10 |cFF9D9D9D[Bleach]|r, 5 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF175-185|r]",
"Craft: 94x |cFFFFFFFF[Bolt of Mageweave]|r",
"Requires: 470 |cFFFFFFFF[Mageweave Cloth]|r",
"",
"[|cFF33FFFF185-205|r]",
"Craft: 20x |cFFFFFFFF[Crimson Silk Vest]|r",
"Requires: 80 |cFFFFFFFF[Bolt of Silk Cloth]|r, 40 |cFF9D9D9D[Red Dye]|r, 40 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF205-215|r]",
"Craft: 10x |cFFFFFFFF[Crimson Silk Pantaloons]|r",
"Requires: 40 |cFFFFFFFF[Bolt of Silk Cloth]|r, 20 |cFF9D9D9D[Red Dye]|r, 20 |cFF9D9D9D[Silken Thread]|r",
"",
"[|cFF33FFFF215-220|r]",
"Craft: 5x |cFF1EFF00[Orange Mageweave Shirt]|r",
"Requires: 5 |cFFFFFFFF[Bolt of Mageweave]|r, 5 |cFF9D9D9D[Orange Dye]|r, 5 |cFF9D9D9D[Heavy Silken Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN:", 
"      |cFF1EFF00[Artisan Tailor]|r (Requires Character Level 35; Raises Cap [225] > [300])",
"WHERE:",
"      |cFFFF0000[H]|r |cFF33FF99[Timothy Worthington]|r / |cFF33FF99[Theramore Isle, Dustwallow Marsh]|r",
"",
"      |cFF66B2FF[A]|r |cFF33FF99[Daryl Stack]|r / |cFF33FF99[Tarren Mill, Hillsbrad Foothills]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF220 - 260|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"Farming Mageweave Cloth",
"------------------------------------------------------------------------------------------------",
"Mob Level Ranges to Farm |cFFFFFFFF[Mageweave Cloth]|r:",
"      |cFFFFFF00Start Level|r: [|cFF33FFFF38|r]",
"      |cFF1EFF00Sweet Spot|r: [|cFF33FFFF45-49|r]",
"      |cFFFF8000Overlap|r: |cFFFFFFFF[Silk Cloth]|r: [|cFF33FFFF38-44|r] | |cFFFFFFFF[Runecloth]|r: 50+",
"      |cFFFF0000End Level|r: [|cFF33FFFF50|r]",
"",
"Best Places to Farm |cFFFFFFFF[Mageweave Cloth]|r:",
"      1.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Feralas [|cFF33FFFF40-50|r]",
"      2.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Tanaris |cFF33FFFF[40-50|r",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF220-230|r]",
"Craft: 10x |cFF1EFF00[Black Mageweave Gloves]|r",
"Requires: 20 |cFFFFFFFF[Bolt of Mageweave]|r, 20 |cFF9D9D9D[Heavy Silken Thread]|r",
"",
"[|cFF33FFFF230-250|r]",
"Craft: 23x |cFF1EFF00[Black Mageweave Headband]|r",
"Requires: 69 |cFFFFFFFF[Bolt of Mageweave]|r, 46 |cFF9D9D9D[Heavy Silken Thread]|r",
"",
"[|cFF33FFFF250-260|r]",
"Craft: 239x |cFFFFFFFF[Bolt of Runecloth]|r",
"Requires: 1195 |cFFFFFFFF[Runecloth]|r",
"",
"[|cFF33FFFF260-280|r]",
"Craft: 25x |cFF1EFF00[Runecloth Belt]|r",
"Requires: 75 |cFFFFFFFF[Bolt of Runecloth]|r, 25 |cFF9D9D9D[Rune Thread]|r",
"",
"      |cFFB2FF66Alternative Recipes|r |cFFFF8000|cFFFFFF00[Auction House]|r|r :",
"      Craft: |cFFFFFFFF[Runecloth Bag]|r",
"      NOTE: More expensive to craft but you can recoup gold from sales",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF260 - 280|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"Farming Runecloth",
"------------------------------------------------------------------------------------------------",
"Mob Level Ranges to Farm |cFFFFFFFF[Runecloth]|r:",
"      |cFFFFFF00Start Level|r: [|cFF33FFFF50|r]",
"      |cFF1EFF00Sweet Spot|r: [|cFF33FFFF55-60|r]",
"      |cFFFF8000Overlap|r: |cFFFFFFFF[Mageweave Cloth]|r: [|cFF33FFFF50-53|r] | |cFFFFFFFF[Felcloth]|r: All 50+ Demons",
"      |cFFFF0000End Level|r: [|cFF33FFFFN/A|r]",
"",
"Best Places to Farm |cFFFFFFFF[Runecloth]|r:",
"      1.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Felwood [|cFF33FFFF48-55|r]|r]",
"      2.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Western Plaguelands [|cFF33FFFF51-58|r]|r",
"      3.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Eastern Plaguelands [|cFF33FFFF53-60|r]|r",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"      |cFF1EFF00[Pattern: Runecloth Bag]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Qia]|r / |cFF66B2FF[Everlook, Winterspring]|r",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF280-290|r]",
"Craft: 18x |cFFFFFFFF[Runecloth Bag]|r",
"Requires: 90 |cFFFFFFFF[Bolt of Runecloth]|r, 36 |cFFFFFFFF[Rugged Leather]|r, 18 |cFF9D9D9D[Rune Thread]|r",
"",
"|cFFB2FF66Alternative Recipes|r",
"      Craft: 8x |cFFFFFFFF[Runecloth Belt]|r",
"      Requires: 24 |cFFFFFFFF[Bolt of Runecloth]|r, 8 |cFF9D9D9D[Rune Thread]|r",
"------------------------------------------------------------------------------------------------",
"ACQUIRE:",
"|cFF1EFF00[Pattern: Runecloth Gloves]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"      |cFFFFD700[N]|r |cFF33FF99[Qia]|r / |cFF66B2FF[Everlook, Winterspring]|r",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF285-300|r] or [|cFF33FFFF290-300|r]",
"Craft: 18x |cFFFFFFFF[Runecloth Gloves]|r",
"Requires: 72 |cFFFFFFFF[Bolt of Runecloth]|r, 72 |cFFFFFFFF[Rugged Leather]|r, 18 |cFF9D9D9D[Rune Thread]|r",
"",
"      |cFFB2FF66Alternative Recipes|r ",
"      NOTE: Check price of |cFF1EFF00Pattern: Runecloth Gloves|r first as baseline",
"",
"      Craft: 20x |cFFFFFFFF[Runecloth Pants]|r",
"      Requires: 200 |cFFFFFFFF[Bolt of Runecloth]|r, 20 |cFF9D9D9D[Rune Thread]|r",
"",
"      Craft: 15x |cFFFFFFFF[Brightcloth Gloves]|r",
"      Requires: 90 |cFFFFFFFF[Bolt of Runecloth]|r, 30 |cFFFFFFFF[Rugged Leather]|r, 15 |cFF9D9D9D[Rune Thread]|r",
"",
"      Craft: 15x |cFFFFFFFF[Brightcloth Robe]|r",
"      Requires: 105 |cFFFFFFFF[Bolt of Runecloth]|r, 15 |cFF9D9D9D[Rune Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"Extra: Farming Felcloth (only drops from Demons)",
"------------------------------------------------------------------------------------------------",
"Mob Level Ranges to Farm |cFFFFFFFF[Felcloth]|r:",
"      |cFFFFFF00Start Level|r: [|cFF33FFFF50|r]",
"      |cFF1EFF00Sweet Spot|r: [|cFF33FFFFNoner]",
"      |cFFFF8000Overlap|r: Usually |cFFFFFFFF[Mageweave]|r: [|cFF33FFFF50-52|r] | |cFFFFFFFF[Runecloth]|r: [|cFF33FFFF50-60|r] (always overlaps",
"      with other cloths)",
"      |cFFFF0000End Level|r: [|cFF33FFFFN/A|r]",
"",
"Best Places to Farm |cFFFFFFFF[Felcloth]|r:",
"      1.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Felwood [|cFF33FFFF48-55|r]",
"      2.|cFFFF0000[H]|r|cFF66B2FF[A]|r |cFF33FF99Azshara|cFF33FFFF[45-55|r",
"------------------------------------------------------------------------------------------------",
}
}