Tailoring = {
buttonText = "Tailoring",
headerText = "THE TAILOR",
content = {
"------------------------------------------------------------------------------------------------",
"Material List",
"------------------------------------------------------------------------------------------------",
"204 |cFFFFFFFF[Linen Cloth]|r",
"55 |cFF9D9D9D[Coarse Thread]|r",
"135 |cFFFFFFFF[Wool Cloth]|r",
"43 |cFF9D9D9D[Fine Thread]|r",
"804 |cFFFFFFFF[Silk Cloth]|r",
"36 |cFF9D9D9D[Blue Dye]|r",
"10 |cFF9D9D9D[Bleach]|r",
"60 |cFF9D9D9D[Red Dye]|r",
"20 |cFF9D9D9D[Silken Thread]|r",
"470 |cFFFFFFFF[Mageweave Cloth]|r",
"5 |cFF9D9D9D[Orange Dye]|r",
"71 |cFF9D9D9D[Heavy Silken Thread]|r",
"1195 |cFFFFFFFF[Runecloth]|r",
"110 |cFFFFFFFF[Rugged Leather]|r",
"61 |cFF9D9D9D[Rune Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"PREFACE",
"------------------------------------------------------------------------------------------------",
"|cFF33FF99Vendors/Trainers|r have faction hostility indicators:",
"|cFFFF0000[H]|r: Friendly with Horde",
"|cFF66B2FF[A]|r: Friendly with Alliance",
"|cFFFFD700[N]|r: Neutral",
"",
"Some |cFF1EFF00Recipes|r may require completing |cFFFFFF00[! Quests]|r or are of |cFFFF8000[Limited supply]|r",
"so you will have to either camp their vendor or purchase from the [Auction House]",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"LEVELING TAILORING",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF1 - 75|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF1-45|r]",
"Craft: 102x |cFFFFFFFF[Bolt of Linen Cloth]|r",
"Requires: 204 |cFFFFFFFF[Linen Cloth]|r",
"NOTE: Stop at 45 if you reach it early",
"",
"[|cFF33FFFF40-70|r]",
"Craft: 40x |cFFFFFFFF[Linen Belt]|r",
"Requires: 40 |cFFFFFFFF[Bolt of Linen Cloth]|r, 40 |cFF9D9D9D[Coarse Thread]|r",
"",
"[|cFF33FFFF70-75|r]",
"Craft: 5x |cFFFFFFFF[Reinforced Linen Cape]|r",
"Requires: 10 |cFFFFFFFF[Bolt of Linen Cloth]|r, 15 |cFF9D9D9D[Coarse Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN: |cFFFFFFFF[Journeyman Tailor]|r (Requires Character Level 10; Raises Cap [75] > [150])",
"WHERE:",
"     |cFFFF0000[H]|r |cFF33FF99[Magar]|r found / |cFF66B2FF[Orgrimmar, Durator]|r",
"     |cFFFF0000[H]|r |cFF33FF99[Rhiannon Davis]|r found / |cFF66B2FF[Undercity, Tirisfal Glades]|r",
"     |cFFFF0000[H]|r |cFF33FF99[Tepa]|r found / |cFF66B2FF[Thunder Bluff, Mulgore]|r",
"",
"     |cFF66B2FF[A]|r |cFF33FF99[Jormund Stonebrow]|r found / |cFF66B2FF[Ironforge, Dun Morogh]|r",
"     |cFF66B2FF[A]|r |cFF33FF99[Sellandus]|r found / |cFF66B2FF[Stormwind City, Elwynn Forest]|r",
"     |cFF66B2FF[A]|r |cFF33FF99[Me'lynn]|r found / |cFF66B2FF[Darnassus, Teldrassil]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF75 - 125|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF75-100|r]",
"Craft: 45x |cFFFFFFFF[Bolt of Woolen Cloth]|r",
"Requires: 135 |cFFFFFFFF[Wool Cloth]|r",
"",
"[|cFF33FFFF100-110|r]",
"Craft: 13x |cFFFFFFFF[Simple Kilt]|r",
"Requires: 52 |cFFFFFFFF[Bolt of Linen Cloth]|r, 13 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF110-125|r]",
"Craft: 15x |cFFFFFFFF[Double-stitched Woolen Shoulders]|r",
"Requires: 45 |cFFFFFFFF[Bolt of Woolen Cloth]|r, 30 |cFF9D9D9D[Fine Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN: |cFFFFFFFF[Expert Tailor]|r (Requires Character Level 20; Raises Cap [150] > [225])",
"WHERE:",
"     |cFFFF0000[H]|r |cFF33FF99[Josef Gregorian]|r found / |cFF66B2FF[Undercity, Tirisfal Glades]|r",
"",
"     |cFF66B2FF[A]|r |cFF33FF99[Georgio Bolero]|r found / |cFF66B2FF[Stormwind City, Elwynn Forest]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF125 - 220|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF125-145|r]",
"Craft: 201x |cFFFFFFFF[Bolt of Silk Cloth]|r",
"Requires: 804 |cFFFFFFFF[Silk Cloth]|r",
"",
"[|cFF33FFFF145-160|r]",
"Craft: 18x |cFFFFFFFF[Azure Silk Hood]|r",
"Requires: 36 |cFFFFFFFF[Bolt of Silk Cloth]|r, 36 |cFF9D9D9D[Blue Dye]|r, 18 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF160-170|r]",
"Craft: 10x |cFFFFFFFF[Silk Headband]|r",
"Requires: 30 |cFFFFFFFF[Bolt of Silk Cloth]|r, 20 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF170-175|r]",
"Craft: 5x |cFFFFFFFF[Formal White Shirt]|r",
"Requires: 15 |cFFFFFFFF[Bolt of Silk Cloth]|r, 10 |cFF9D9D9D[Bleach]|r, 5 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF175-185|r]",
"Craft: 94x |cFFFFFFFF[Bolt of Mageweave]|r",
"Requires: 470 |cFFFFFFFF[Mageweave Cloth]|r",
"",
"[|cFF33FFFF185-205|r]",
"Craft: 20x |cFFFFFFFF[Crimson Silk Vest]|r",
"Requires: 80 |cFFFFFFFF[Bolt of Silk Cloth]|r, 40 |cFF9D9D9D[Red Dye]|r, 40 |cFF9D9D9D[Fine Thread]|r",
"",
"[|cFF33FFFF205-215|r]",
"Craft: 10x |cFFFFFFFF[Crimson Silk Pantaloons]|r",
"Requires: 40 |cFFFFFFFF[Bolt of Silk Cloth]|r, 20 |cFF9D9D9D[Red Dye]|r, 20 |cFF9D9D9D[Silken Thread]|r",
"",
"[|cFF33FFFF215-220|r]",
"Craft: 5x |cFFFFFFFF[Orange Mageweave Shirt]|r",
"Requires: 5 |cFFFFFFFF[Bolt of Mageweave]|r, 5 |cFF9D9D9D[Orange Dye]|r, 5 |cFF9D9D9D[Heavy Silken Thread]|r",
"",
"------------------------------------------------------------------------------------------------",
"TRAIN: |cFFFFFFFF[Artisan Tailor]|r (Requires Character Level 35; Raises Cap [225] > [300])",
"WHERE:",
"     |cFFFF0000[H]|r |cFF33FF99[Timothy Worthington]|r found / |cFF66B2FF[Theramore Isle, Dustwallow Marsh]|r",
"",
"     |cFF66B2FF[A]|r |cFF33FF99[Daryl Stack]|r found / |cFF66B2FF[Tarren Mill, Hillsbrad Foothills]|r",
"------------------------------------------------------------------------------------------------",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF220 - 280|r]",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF220-230|r]",
"Craft: 10x |cFFFFFFFF[Black Mageweave Gloves]|r",
"Requires: 20 |cFFFFFFFF[Bolt of Mageweave]|r, 20 |cFF9D9D9D[Heavy Silken Thread]|r",
"",
"[|cFF33FFFF230-250|r]",
"Craft: 23x |cFFFFFFFF[Black Mageweave Headband]|r",
"Requires: 69 |cFFFFFFFF[Bolt of Mageweave]|r, 46 |cFF9D9D9D[Heavy Silken Thread]|r",
"",
"[|cFF33FFFF250-260|r]",
"Craft: 239x |cFFFFFFFF[Bolt of Runecloth]|r",
"Requires: 1195 |cFFFFFFFF[Runecloth]|r",
"",
"[|cFF33FFFF260-280|r]",
"Craft: 25x |cFFFFFFFF[Runecloth Belt]|r",
"Requires: 75 |cFFFFFFFF[Bolt of Runecloth]|r, 25 |cFF9D9D9D[Rune Thread]|r",
"",
"Alternative if selling at Auction House:",
"Craft: |cFFFFFFFF[Runecloth Bag]|r",
"NOTE: Bags are more expensive but you can recoup gold from sales",
"",
"------------------------------------------------------------------------------------------------",
"|cFF33FFFFLevels:|r [|cFF33FFFF280 - 300|r]",
"------------------------------------------------------------------------------------------------",
"------------------------------------------------------------------------------------------------",
"ACQUIRE: |cFF1EFF00[Pattern: Runecloth Bag]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"     |cFFFFD700[N]|r |cFF33FF99[Qia]|r found / |cFF66B2FF[Everlook, Winterspring]|r",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF280-290|r]",
"Craft: 18x |cFFFFFFFF[Runecloth Bag]|r",
"Requires: 90 |cFFFFFFFF[Bolt of Runecloth]|r, 36 |cFFFFFFFF[Rugged Leather]|r, 18 |cFF9D9D9D[Rune Thread]|r",
"",
"|cFFB2FF66Alternative Recipes|r",
"[|cFF33FFFF280-285|r]",
"Craft: 8x |cFFFFFFFF[Runecloth Belt]|r",
"Requires: 24 |cFFFFFFFF[Bolt of Runecloth]|r, 8 |cFF9D9D9D[Rune Thread]|r",
"------------------------------------------------------------------------------------------------",
"ACQUIRE: |cFF1EFF00[Pattern: Runecloth Gloves]|r |cFFFF8000[Limited supply]|r",
"WHERE:",
"     |cFFFFD700[N]|r |cFF33FF99[Qia]|r found / |cFF66B2FF[Everlook, Winterspring]|r",
"------------------------------------------------------------------------------------------------",
"[|cFF33FFFF290-300|r] or [|cFF33FFFF285-300|r]",
"Craft: 18x |cFFFFFFFF[Runecloth Gloves]|r",
"Requires: 72 |cFFFFFFFF[Bolt of Runecloth]|r, 72 |cFFFFFFFF[Rugged Leather]|r, 18 |cFF9D9D9D[Rune Thread]|r",
"",
"|cFFB2FF66Alternative Recipes|r ",
"NOTE: Check price of |cFF1EFF00Pattern: Runecloth Gloves|r first as baseline",
"",
"Craft: 20x |cFFFFFFFF[Runecloth Pants]|r",
"Requires: 200 |cFFFFFFFF[Bolt of Runecloth]|r, 20 |cFF9D9D9D[Rune Thread]|r",
"",
"Craft: 15x |cFFFFFFFF[Brightcloth Gloves]|r",
"Requires: 90 |cFFFFFFFF[Bolt of Runecloth]|r, 30 |cFFFFFFFF[Rugged Leather]|r, 15 |cFF9D9D9D[Rune Thread]|r",
"",
"Craft: 15x |cFFFFFFFF[Brightcloth Robe]|r",
"Requires: 105 |cFFFFFFFF[Bolt of Runecloth]|r, 15 |cFF9D9D9D[Rune Thread]|r"
}
}